
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Module
 * 
 */
export type Module = Prisma.ModuleModel
/**
 * Model Screen
 * 
 */
export type Screen = Prisma.ScreenModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model ProfileScreen
 * 
 */
export type ProfileScreen = Prisma.ProfileScreenModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model ProfilePermission
 * 
 */
export type ProfilePermission = Prisma.ProfilePermissionModel
/**
 * Model UserProfile
 * 
 */
export type UserProfile = Prisma.UserProfileModel
/**
 * Model CheckIn
 * 
 */
export type CheckIn = Prisma.CheckInModel
/**
 * Model Gym
 * 
 */
export type Gym = Prisma.GymModel
/**
 * Model EmailVerification
 * 
 */
export type EmailVerification = Prisma.EmailVerificationModel
/**
 * Model EmailChange
 * 
 */
export type EmailChange = Prisma.EmailChangeModel
/**
 * Model PasswordReset
 * 
 */
export type PasswordReset = Prisma.PasswordResetModel
/**
 * Model RevokedToken
 * 
 */
export type RevokedToken = Prisma.RevokedTokenModel
/**
 * Model Notice
 * 
 */
export type Notice = Prisma.NoticeModel
