
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Module'
export type * from './models/Screen'
export type * from './models/Profile'
export type * from './models/ProfileScreen'
export type * from './models/Permission'
export type * from './models/ProfilePermission'
export type * from './models/UserProfile'
export type * from './models/CheckIn'
export type * from './models/Gym'
export type * from './models/EmailVerification'
export type * from './models/EmailChange'
export type * from './models/PasswordReset'
export type * from './models/RevokedToken'
export type * from './commonInputTypes'