
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Module: 'Module',
  Screen: 'Screen',
  Profile: 'Profile',
  ProfileScreen: 'ProfileScreen',
  Permission: 'Permission',
  ProfilePermission: 'ProfilePermission',
  UserProfile: 'UserProfile',
  CheckIn: 'CheckIn',
  Gym: 'Gym',
  EmailVerification: 'EmailVerification',
  EmailChange: 'EmailChange',
  PasswordReset: 'PasswordReset',
  RevokedToken: 'RevokedToken'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password_hash: 'password_hash',
  role: 'role',
  is_verified: 'is_verified',
  is_active: 'is_active',
  default_screen_key: 'default_screen_key',
  created_at: 'created_at',
  password_changed_at: 'password_changed_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ModuleScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  order: 'order',
  is_system: 'is_system',
  is_active: 'is_active'
} as const

export type ModuleScalarFieldEnum = (typeof ModuleScalarFieldEnum)[keyof typeof ModuleScalarFieldEnum]


export const ScreenScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  path: 'path',
  description: 'description',
  order: 'order',
  is_system: 'is_system',
  is_active: 'is_active',
  is_enabled: 'is_enabled',
  module_id: 'module_id'
} as const

export type ScreenScalarFieldEnum = (typeof ScreenScalarFieldEnum)[keyof typeof ScreenScalarFieldEnum]


export const ProfileScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  is_system: 'is_system',
  is_default: 'is_default',
  is_active: 'is_active',
  created_at: 'created_at',
  default_screen_id: 'default_screen_id'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const ProfileScreenScalarFieldEnum = {
  profile_id: 'profile_id',
  screen_id: 'screen_id'
} as const

export type ProfileScreenScalarFieldEnum = (typeof ProfileScreenScalarFieldEnum)[keyof typeof ProfileScreenScalarFieldEnum]


export const PermissionScalarFieldEnum = {
  id: 'id',
  screen_id: 'screen_id',
  action: 'action',
  label: 'label',
  is_system: 'is_system'
} as const

export type PermissionScalarFieldEnum = (typeof PermissionScalarFieldEnum)[keyof typeof PermissionScalarFieldEnum]


export const ProfilePermissionScalarFieldEnum = {
  profile_id: 'profile_id',
  permission_id: 'permission_id'
} as const

export type ProfilePermissionScalarFieldEnum = (typeof ProfilePermissionScalarFieldEnum)[keyof typeof ProfilePermissionScalarFieldEnum]


export const UserProfileScalarFieldEnum = {
  user_id: 'user_id',
  profile_id: 'profile_id'
} as const

export type UserProfileScalarFieldEnum = (typeof UserProfileScalarFieldEnum)[keyof typeof UserProfileScalarFieldEnum]


export const CheckInScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  validated_at: 'validated_at',
  user_id: 'user_id',
  gym_id: 'gym_id'
} as const

export type CheckInScalarFieldEnum = (typeof CheckInScalarFieldEnum)[keyof typeof CheckInScalarFieldEnum]


export const GymScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  phone: 'phone',
  latitude: 'latitude',
  longitude: 'longitude',
  is_active: 'is_active'
} as const

export type GymScalarFieldEnum = (typeof GymScalarFieldEnum)[keyof typeof GymScalarFieldEnum]


export const EmailVerificationScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  link_token: 'link_token',
  otp_code: 'otp_code',
  attempts: 'attempts',
  expires_at: 'expires_at',
  used_at: 'used_at',
  created_at: 'created_at'
} as const

export type EmailVerificationScalarFieldEnum = (typeof EmailVerificationScalarFieldEnum)[keyof typeof EmailVerificationScalarFieldEnum]


export const EmailChangeScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  new_email: 'new_email',
  link_token: 'link_token',
  otp_code: 'otp_code',
  attempts: 'attempts',
  expires_at: 'expires_at',
  used_at: 'used_at',
  created_at: 'created_at'
} as const

export type EmailChangeScalarFieldEnum = (typeof EmailChangeScalarFieldEnum)[keyof typeof EmailChangeScalarFieldEnum]


export const PasswordResetScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  link_token_hash: 'link_token_hash',
  otp_code_hash: 'otp_code_hash',
  attempts: 'attempts',
  expires_at: 'expires_at',
  used_at: 'used_at',
  created_at: 'created_at'
} as const

export type PasswordResetScalarFieldEnum = (typeof PasswordResetScalarFieldEnum)[keyof typeof PasswordResetScalarFieldEnum]


export const RevokedTokenScalarFieldEnum = {
  jti: 'jti',
  expires_at: 'expires_at',
  created_at: 'created_at'
} as const

export type RevokedTokenScalarFieldEnum = (typeof RevokedTokenScalarFieldEnum)[keyof typeof RevokedTokenScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password_hash: 'password_hash',
  default_screen_key: 'default_screen_key'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const ModuleOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description'
} as const

export type ModuleOrderByRelevanceFieldEnum = (typeof ModuleOrderByRelevanceFieldEnum)[keyof typeof ModuleOrderByRelevanceFieldEnum]


export const ScreenOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  path: 'path',
  description: 'description',
  module_id: 'module_id'
} as const

export type ScreenOrderByRelevanceFieldEnum = (typeof ScreenOrderByRelevanceFieldEnum)[keyof typeof ScreenOrderByRelevanceFieldEnum]


export const ProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  default_screen_id: 'default_screen_id'
} as const

export type ProfileOrderByRelevanceFieldEnum = (typeof ProfileOrderByRelevanceFieldEnum)[keyof typeof ProfileOrderByRelevanceFieldEnum]


export const ProfileScreenOrderByRelevanceFieldEnum = {
  profile_id: 'profile_id',
  screen_id: 'screen_id'
} as const

export type ProfileScreenOrderByRelevanceFieldEnum = (typeof ProfileScreenOrderByRelevanceFieldEnum)[keyof typeof ProfileScreenOrderByRelevanceFieldEnum]


export const PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  screen_id: 'screen_id',
  label: 'label'
} as const

export type PermissionOrderByRelevanceFieldEnum = (typeof PermissionOrderByRelevanceFieldEnum)[keyof typeof PermissionOrderByRelevanceFieldEnum]


export const ProfilePermissionOrderByRelevanceFieldEnum = {
  profile_id: 'profile_id',
  permission_id: 'permission_id'
} as const

export type ProfilePermissionOrderByRelevanceFieldEnum = (typeof ProfilePermissionOrderByRelevanceFieldEnum)[keyof typeof ProfilePermissionOrderByRelevanceFieldEnum]


export const UserProfileOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  profile_id: 'profile_id'
} as const

export type UserProfileOrderByRelevanceFieldEnum = (typeof UserProfileOrderByRelevanceFieldEnum)[keyof typeof UserProfileOrderByRelevanceFieldEnum]


export const CheckInOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  gym_id: 'gym_id'
} as const

export type CheckInOrderByRelevanceFieldEnum = (typeof CheckInOrderByRelevanceFieldEnum)[keyof typeof CheckInOrderByRelevanceFieldEnum]


export const GymOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  phone: 'phone'
} as const

export type GymOrderByRelevanceFieldEnum = (typeof GymOrderByRelevanceFieldEnum)[keyof typeof GymOrderByRelevanceFieldEnum]


export const EmailVerificationOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  link_token: 'link_token',
  otp_code: 'otp_code'
} as const

export type EmailVerificationOrderByRelevanceFieldEnum = (typeof EmailVerificationOrderByRelevanceFieldEnum)[keyof typeof EmailVerificationOrderByRelevanceFieldEnum]


export const EmailChangeOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  new_email: 'new_email',
  link_token: 'link_token',
  otp_code: 'otp_code'
} as const

export type EmailChangeOrderByRelevanceFieldEnum = (typeof EmailChangeOrderByRelevanceFieldEnum)[keyof typeof EmailChangeOrderByRelevanceFieldEnum]


export const PasswordResetOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  link_token_hash: 'link_token_hash',
  otp_code_hash: 'otp_code_hash'
} as const

export type PasswordResetOrderByRelevanceFieldEnum = (typeof PasswordResetOrderByRelevanceFieldEnum)[keyof typeof PasswordResetOrderByRelevanceFieldEnum]


export const RevokedTokenOrderByRelevanceFieldEnum = {
  jti: 'jti'
} as const

export type RevokedTokenOrderByRelevanceFieldEnum = (typeof RevokedTokenOrderByRelevanceFieldEnum)[keyof typeof RevokedTokenOrderByRelevanceFieldEnum]

