
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProfileScreen` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProfileScreen
 * 
 */
export type ProfileScreenModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfileScreenPayload>

export type AggregateProfileScreen = {
  _count: ProfileScreenCountAggregateOutputType | null
  _min: ProfileScreenMinAggregateOutputType | null
  _max: ProfileScreenMaxAggregateOutputType | null
}

export type ProfileScreenMinAggregateOutputType = {
  profile_id: string | null
  screen_id: string | null
  can_view: boolean | null
  can_create: boolean | null
  can_edit: boolean | null
  can_delete: boolean | null
  is_default: boolean | null
}

export type ProfileScreenMaxAggregateOutputType = {
  profile_id: string | null
  screen_id: string | null
  can_view: boolean | null
  can_create: boolean | null
  can_edit: boolean | null
  can_delete: boolean | null
  is_default: boolean | null
}

export type ProfileScreenCountAggregateOutputType = {
  profile_id: number
  screen_id: number
  can_view: number
  can_create: number
  can_edit: number
  can_delete: number
  is_default: number
  _all: number
}


export type ProfileScreenMinAggregateInputType = {
  profile_id?: true
  screen_id?: true
  can_view?: true
  can_create?: true
  can_edit?: true
  can_delete?: true
  is_default?: true
}

export type ProfileScreenMaxAggregateInputType = {
  profile_id?: true
  screen_id?: true
  can_view?: true
  can_create?: true
  can_edit?: true
  can_delete?: true
  is_default?: true
}

export type ProfileScreenCountAggregateInputType = {
  profile_id?: true
  screen_id?: true
  can_view?: true
  can_create?: true
  can_edit?: true
  can_delete?: true
  is_default?: true
  _all?: true
}

export type ProfileScreenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileScreen to aggregate.
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileScreens to fetch.
   */
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileScreens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileScreens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProfileScreens
  **/
  _count?: true | ProfileScreenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileScreenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileScreenMaxAggregateInputType
}

export type GetProfileScreenAggregateType<T extends ProfileScreenAggregateArgs> = {
      [P in keyof T & keyof AggregateProfileScreen]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfileScreen[P]>
    : Prisma.GetScalarType<T[P], AggregateProfileScreen[P]>
}




export type ProfileScreenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileScreenWhereInput
  orderBy?: Prisma.ProfileScreenOrderByWithAggregationInput | Prisma.ProfileScreenOrderByWithAggregationInput[]
  by: Prisma.ProfileScreenScalarFieldEnum[] | Prisma.ProfileScreenScalarFieldEnum
  having?: Prisma.ProfileScreenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileScreenCountAggregateInputType | true
  _min?: ProfileScreenMinAggregateInputType
  _max?: ProfileScreenMaxAggregateInputType
}

export type ProfileScreenGroupByOutputType = {
  profile_id: string
  screen_id: string
  can_view: boolean
  can_create: boolean
  can_edit: boolean
  can_delete: boolean
  is_default: boolean
  _count: ProfileScreenCountAggregateOutputType | null
  _min: ProfileScreenMinAggregateOutputType | null
  _max: ProfileScreenMaxAggregateOutputType | null
}

export type GetProfileScreenGroupByPayload<T extends ProfileScreenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileScreenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileScreenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileScreenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileScreenGroupByOutputType[P]>
      }
    >
  >



export type ProfileScreenWhereInput = {
  AND?: Prisma.ProfileScreenWhereInput | Prisma.ProfileScreenWhereInput[]
  OR?: Prisma.ProfileScreenWhereInput[]
  NOT?: Prisma.ProfileScreenWhereInput | Prisma.ProfileScreenWhereInput[]
  profile_id?: Prisma.StringFilter<"ProfileScreen"> | string
  screen_id?: Prisma.StringFilter<"ProfileScreen"> | string
  can_view?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_create?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_edit?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_delete?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  is_default?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  screen?: Prisma.XOR<Prisma.ScreenScalarRelationFilter, Prisma.ScreenWhereInput>
}

export type ProfileScreenOrderByWithRelationInput = {
  profile_id?: Prisma.SortOrder
  screen_id?: Prisma.SortOrder
  can_view?: Prisma.SortOrder
  can_create?: Prisma.SortOrder
  can_edit?: Prisma.SortOrder
  can_delete?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  profile?: Prisma.ProfileOrderByWithRelationInput
  screen?: Prisma.ScreenOrderByWithRelationInput
  _relevance?: Prisma.ProfileScreenOrderByRelevanceInput
}

export type ProfileScreenWhereUniqueInput = Prisma.AtLeast<{
  profile_id_screen_id?: Prisma.ProfileScreenProfile_idScreen_idCompoundUniqueInput
  AND?: Prisma.ProfileScreenWhereInput | Prisma.ProfileScreenWhereInput[]
  OR?: Prisma.ProfileScreenWhereInput[]
  NOT?: Prisma.ProfileScreenWhereInput | Prisma.ProfileScreenWhereInput[]
  profile_id?: Prisma.StringFilter<"ProfileScreen"> | string
  screen_id?: Prisma.StringFilter<"ProfileScreen"> | string
  can_view?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_create?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_edit?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_delete?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  is_default?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  screen?: Prisma.XOR<Prisma.ScreenScalarRelationFilter, Prisma.ScreenWhereInput>
}, "profile_id_screen_id">

export type ProfileScreenOrderByWithAggregationInput = {
  profile_id?: Prisma.SortOrder
  screen_id?: Prisma.SortOrder
  can_view?: Prisma.SortOrder
  can_create?: Prisma.SortOrder
  can_edit?: Prisma.SortOrder
  can_delete?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  _count?: Prisma.ProfileScreenCountOrderByAggregateInput
  _max?: Prisma.ProfileScreenMaxOrderByAggregateInput
  _min?: Prisma.ProfileScreenMinOrderByAggregateInput
}

export type ProfileScreenScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileScreenScalarWhereWithAggregatesInput | Prisma.ProfileScreenScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileScreenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileScreenScalarWhereWithAggregatesInput | Prisma.ProfileScreenScalarWhereWithAggregatesInput[]
  profile_id?: Prisma.StringWithAggregatesFilter<"ProfileScreen"> | string
  screen_id?: Prisma.StringWithAggregatesFilter<"ProfileScreen"> | string
  can_view?: Prisma.BoolWithAggregatesFilter<"ProfileScreen"> | boolean
  can_create?: Prisma.BoolWithAggregatesFilter<"ProfileScreen"> | boolean
  can_edit?: Prisma.BoolWithAggregatesFilter<"ProfileScreen"> | boolean
  can_delete?: Prisma.BoolWithAggregatesFilter<"ProfileScreen"> | boolean
  is_default?: Prisma.BoolWithAggregatesFilter<"ProfileScreen"> | boolean
}

export type ProfileScreenCreateInput = {
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
  profile: Prisma.ProfileCreateNestedOneWithoutScreensInput
  screen: Prisma.ScreenCreateNestedOneWithoutGrantsInput
}

export type ProfileScreenUncheckedCreateInput = {
  profile_id: string
  screen_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenUpdateInput = {
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  profile?: Prisma.ProfileUpdateOneRequiredWithoutScreensNestedInput
  screen?: Prisma.ScreenUpdateOneRequiredWithoutGrantsNestedInput
}

export type ProfileScreenUncheckedUpdateInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  screen_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenCreateManyInput = {
  profile_id: string
  screen_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenUpdateManyMutationInput = {
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenUncheckedUpdateManyInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  screen_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenListRelationFilter = {
  every?: Prisma.ProfileScreenWhereInput
  some?: Prisma.ProfileScreenWhereInput
  none?: Prisma.ProfileScreenWhereInput
}

export type ProfileScreenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProfileScreenOrderByRelevanceInput = {
  fields: Prisma.ProfileScreenOrderByRelevanceFieldEnum | Prisma.ProfileScreenOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProfileScreenProfile_idScreen_idCompoundUniqueInput = {
  profile_id: string
  screen_id: string
}

export type ProfileScreenCountOrderByAggregateInput = {
  profile_id?: Prisma.SortOrder
  screen_id?: Prisma.SortOrder
  can_view?: Prisma.SortOrder
  can_create?: Prisma.SortOrder
  can_edit?: Prisma.SortOrder
  can_delete?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
}

export type ProfileScreenMaxOrderByAggregateInput = {
  profile_id?: Prisma.SortOrder
  screen_id?: Prisma.SortOrder
  can_view?: Prisma.SortOrder
  can_create?: Prisma.SortOrder
  can_edit?: Prisma.SortOrder
  can_delete?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
}

export type ProfileScreenMinOrderByAggregateInput = {
  profile_id?: Prisma.SortOrder
  screen_id?: Prisma.SortOrder
  can_view?: Prisma.SortOrder
  can_create?: Prisma.SortOrder
  can_edit?: Prisma.SortOrder
  can_delete?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
}

export type ProfileScreenCreateNestedManyWithoutScreenInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput> | Prisma.ProfileScreenCreateWithoutScreenInput[] | Prisma.ProfileScreenUncheckedCreateWithoutScreenInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutScreenInput | Prisma.ProfileScreenCreateOrConnectWithoutScreenInput[]
  createMany?: Prisma.ProfileScreenCreateManyScreenInputEnvelope
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
}

export type ProfileScreenUncheckedCreateNestedManyWithoutScreenInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput> | Prisma.ProfileScreenCreateWithoutScreenInput[] | Prisma.ProfileScreenUncheckedCreateWithoutScreenInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutScreenInput | Prisma.ProfileScreenCreateOrConnectWithoutScreenInput[]
  createMany?: Prisma.ProfileScreenCreateManyScreenInputEnvelope
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
}

export type ProfileScreenUpdateManyWithoutScreenNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput> | Prisma.ProfileScreenCreateWithoutScreenInput[] | Prisma.ProfileScreenUncheckedCreateWithoutScreenInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutScreenInput | Prisma.ProfileScreenCreateOrConnectWithoutScreenInput[]
  upsert?: Prisma.ProfileScreenUpsertWithWhereUniqueWithoutScreenInput | Prisma.ProfileScreenUpsertWithWhereUniqueWithoutScreenInput[]
  createMany?: Prisma.ProfileScreenCreateManyScreenInputEnvelope
  set?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  disconnect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  delete?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  update?: Prisma.ProfileScreenUpdateWithWhereUniqueWithoutScreenInput | Prisma.ProfileScreenUpdateWithWhereUniqueWithoutScreenInput[]
  updateMany?: Prisma.ProfileScreenUpdateManyWithWhereWithoutScreenInput | Prisma.ProfileScreenUpdateManyWithWhereWithoutScreenInput[]
  deleteMany?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
}

export type ProfileScreenUncheckedUpdateManyWithoutScreenNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput> | Prisma.ProfileScreenCreateWithoutScreenInput[] | Prisma.ProfileScreenUncheckedCreateWithoutScreenInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutScreenInput | Prisma.ProfileScreenCreateOrConnectWithoutScreenInput[]
  upsert?: Prisma.ProfileScreenUpsertWithWhereUniqueWithoutScreenInput | Prisma.ProfileScreenUpsertWithWhereUniqueWithoutScreenInput[]
  createMany?: Prisma.ProfileScreenCreateManyScreenInputEnvelope
  set?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  disconnect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  delete?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  update?: Prisma.ProfileScreenUpdateWithWhereUniqueWithoutScreenInput | Prisma.ProfileScreenUpdateWithWhereUniqueWithoutScreenInput[]
  updateMany?: Prisma.ProfileScreenUpdateManyWithWhereWithoutScreenInput | Prisma.ProfileScreenUpdateManyWithWhereWithoutScreenInput[]
  deleteMany?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
}

export type ProfileScreenCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput> | Prisma.ProfileScreenCreateWithoutProfileInput[] | Prisma.ProfileScreenUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutProfileInput | Prisma.ProfileScreenCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.ProfileScreenCreateManyProfileInputEnvelope
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
}

export type ProfileScreenUncheckedCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput> | Prisma.ProfileScreenCreateWithoutProfileInput[] | Prisma.ProfileScreenUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutProfileInput | Prisma.ProfileScreenCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.ProfileScreenCreateManyProfileInputEnvelope
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
}

export type ProfileScreenUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput> | Prisma.ProfileScreenCreateWithoutProfileInput[] | Prisma.ProfileScreenUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutProfileInput | Prisma.ProfileScreenCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.ProfileScreenUpsertWithWhereUniqueWithoutProfileInput | Prisma.ProfileScreenUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.ProfileScreenCreateManyProfileInputEnvelope
  set?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  disconnect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  delete?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  update?: Prisma.ProfileScreenUpdateWithWhereUniqueWithoutProfileInput | Prisma.ProfileScreenUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.ProfileScreenUpdateManyWithWhereWithoutProfileInput | Prisma.ProfileScreenUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
}

export type ProfileScreenUncheckedUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput> | Prisma.ProfileScreenCreateWithoutProfileInput[] | Prisma.ProfileScreenUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileScreenCreateOrConnectWithoutProfileInput | Prisma.ProfileScreenCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.ProfileScreenUpsertWithWhereUniqueWithoutProfileInput | Prisma.ProfileScreenUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.ProfileScreenCreateManyProfileInputEnvelope
  set?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  disconnect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  delete?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  connect?: Prisma.ProfileScreenWhereUniqueInput | Prisma.ProfileScreenWhereUniqueInput[]
  update?: Prisma.ProfileScreenUpdateWithWhereUniqueWithoutProfileInput | Prisma.ProfileScreenUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.ProfileScreenUpdateManyWithWhereWithoutProfileInput | Prisma.ProfileScreenUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
}

export type ProfileScreenCreateWithoutScreenInput = {
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
  profile: Prisma.ProfileCreateNestedOneWithoutScreensInput
}

export type ProfileScreenUncheckedCreateWithoutScreenInput = {
  profile_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenCreateOrConnectWithoutScreenInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput>
}

export type ProfileScreenCreateManyScreenInputEnvelope = {
  data: Prisma.ProfileScreenCreateManyScreenInput | Prisma.ProfileScreenCreateManyScreenInput[]
  skipDuplicates?: boolean
}

export type ProfileScreenUpsertWithWhereUniqueWithoutScreenInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfileScreenUpdateWithoutScreenInput, Prisma.ProfileScreenUncheckedUpdateWithoutScreenInput>
  create: Prisma.XOR<Prisma.ProfileScreenCreateWithoutScreenInput, Prisma.ProfileScreenUncheckedCreateWithoutScreenInput>
}

export type ProfileScreenUpdateWithWhereUniqueWithoutScreenInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfileScreenUpdateWithoutScreenInput, Prisma.ProfileScreenUncheckedUpdateWithoutScreenInput>
}

export type ProfileScreenUpdateManyWithWhereWithoutScreenInput = {
  where: Prisma.ProfileScreenScalarWhereInput
  data: Prisma.XOR<Prisma.ProfileScreenUpdateManyMutationInput, Prisma.ProfileScreenUncheckedUpdateManyWithoutScreenInput>
}

export type ProfileScreenScalarWhereInput = {
  AND?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
  OR?: Prisma.ProfileScreenScalarWhereInput[]
  NOT?: Prisma.ProfileScreenScalarWhereInput | Prisma.ProfileScreenScalarWhereInput[]
  profile_id?: Prisma.StringFilter<"ProfileScreen"> | string
  screen_id?: Prisma.StringFilter<"ProfileScreen"> | string
  can_view?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_create?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_edit?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  can_delete?: Prisma.BoolFilter<"ProfileScreen"> | boolean
  is_default?: Prisma.BoolFilter<"ProfileScreen"> | boolean
}

export type ProfileScreenCreateWithoutProfileInput = {
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
  screen: Prisma.ScreenCreateNestedOneWithoutGrantsInput
}

export type ProfileScreenUncheckedCreateWithoutProfileInput = {
  screen_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenCreateOrConnectWithoutProfileInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput>
}

export type ProfileScreenCreateManyProfileInputEnvelope = {
  data: Prisma.ProfileScreenCreateManyProfileInput | Prisma.ProfileScreenCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type ProfileScreenUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfileScreenUpdateWithoutProfileInput, Prisma.ProfileScreenUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.ProfileScreenCreateWithoutProfileInput, Prisma.ProfileScreenUncheckedCreateWithoutProfileInput>
}

export type ProfileScreenUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.ProfileScreenWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfileScreenUpdateWithoutProfileInput, Prisma.ProfileScreenUncheckedUpdateWithoutProfileInput>
}

export type ProfileScreenUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.ProfileScreenScalarWhereInput
  data: Prisma.XOR<Prisma.ProfileScreenUpdateManyMutationInput, Prisma.ProfileScreenUncheckedUpdateManyWithoutProfileInput>
}

export type ProfileScreenCreateManyScreenInput = {
  profile_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenUpdateWithoutScreenInput = {
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  profile?: Prisma.ProfileUpdateOneRequiredWithoutScreensNestedInput
}

export type ProfileScreenUncheckedUpdateWithoutScreenInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenUncheckedUpdateManyWithoutScreenInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenCreateManyProfileInput = {
  screen_id: string
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenUpdateWithoutProfileInput = {
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  screen?: Prisma.ScreenUpdateOneRequiredWithoutGrantsNestedInput
}

export type ProfileScreenUncheckedUpdateWithoutProfileInput = {
  screen_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ProfileScreenUncheckedUpdateManyWithoutProfileInput = {
  screen_id?: Prisma.StringFieldUpdateOperationsInput | string
  can_view?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_create?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_edit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  can_delete?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type ProfileScreenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  profile_id?: boolean
  screen_id?: boolean
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  screen?: boolean | Prisma.ScreenDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profileScreen"]>



export type ProfileScreenSelectScalar = {
  profile_id?: boolean
  screen_id?: boolean
  can_view?: boolean
  can_create?: boolean
  can_edit?: boolean
  can_delete?: boolean
  is_default?: boolean
}

export type ProfileScreenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"profile_id" | "screen_id" | "can_view" | "can_create" | "can_edit" | "can_delete" | "is_default", ExtArgs["result"]["profileScreen"]>
export type ProfileScreenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  screen?: boolean | Prisma.ScreenDefaultArgs<ExtArgs>
}

export type $ProfileScreenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProfileScreen"
  objects: {
    profile: Prisma.$ProfilePayload<ExtArgs>
    screen: Prisma.$ScreenPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    profile_id: string
    screen_id: string
    can_view: boolean
    can_create: boolean
    can_edit: boolean
    can_delete: boolean
    is_default: boolean
  }, ExtArgs["result"]["profileScreen"]>
  composites: {}
}

export type ProfileScreenGetPayload<S extends boolean | null | undefined | ProfileScreenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload, S>

export type ProfileScreenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileScreenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileScreenCountAggregateInputType | true
  }

export interface ProfileScreenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProfileScreen'], meta: { name: 'ProfileScreen' } }
  /**
   * Find zero or one ProfileScreen that matches the filter.
   * @param {ProfileScreenFindUniqueArgs} args - Arguments to find a ProfileScreen
   * @example
   * // Get one ProfileScreen
   * const profileScreen = await prisma.profileScreen.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileScreenFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileScreenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProfileScreen that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileScreenFindUniqueOrThrowArgs} args - Arguments to find a ProfileScreen
   * @example
   * // Get one ProfileScreen
   * const profileScreen = await prisma.profileScreen.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileScreenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileScreenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileScreen that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenFindFirstArgs} args - Arguments to find a ProfileScreen
   * @example
   * // Get one ProfileScreen
   * const profileScreen = await prisma.profileScreen.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileScreenFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileScreenFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileScreen that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenFindFirstOrThrowArgs} args - Arguments to find a ProfileScreen
   * @example
   * // Get one ProfileScreen
   * const profileScreen = await prisma.profileScreen.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileScreenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileScreenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProfileScreens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProfileScreens
   * const profileScreens = await prisma.profileScreen.findMany()
   * 
   * // Get first 10 ProfileScreens
   * const profileScreens = await prisma.profileScreen.findMany({ take: 10 })
   * 
   * // Only select the `profile_id`
   * const profileScreenWithProfile_idOnly = await prisma.profileScreen.findMany({ select: { profile_id: true } })
   * 
   */
  findMany<T extends ProfileScreenFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileScreenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProfileScreen.
   * @param {ProfileScreenCreateArgs} args - Arguments to create a ProfileScreen.
   * @example
   * // Create one ProfileScreen
   * const ProfileScreen = await prisma.profileScreen.create({
   *   data: {
   *     // ... data to create a ProfileScreen
   *   }
   * })
   * 
   */
  create<T extends ProfileScreenCreateArgs>(args: Prisma.SelectSubset<T, ProfileScreenCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProfileScreens.
   * @param {ProfileScreenCreateManyArgs} args - Arguments to create many ProfileScreens.
   * @example
   * // Create many ProfileScreens
   * const profileScreen = await prisma.profileScreen.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileScreenCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileScreenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ProfileScreen.
   * @param {ProfileScreenDeleteArgs} args - Arguments to delete one ProfileScreen.
   * @example
   * // Delete one ProfileScreen
   * const ProfileScreen = await prisma.profileScreen.delete({
   *   where: {
   *     // ... filter to delete one ProfileScreen
   *   }
   * })
   * 
   */
  delete<T extends ProfileScreenDeleteArgs>(args: Prisma.SelectSubset<T, ProfileScreenDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProfileScreen.
   * @param {ProfileScreenUpdateArgs} args - Arguments to update one ProfileScreen.
   * @example
   * // Update one ProfileScreen
   * const profileScreen = await prisma.profileScreen.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileScreenUpdateArgs>(args: Prisma.SelectSubset<T, ProfileScreenUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProfileScreens.
   * @param {ProfileScreenDeleteManyArgs} args - Arguments to filter ProfileScreens to delete.
   * @example
   * // Delete a few ProfileScreens
   * const { count } = await prisma.profileScreen.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileScreenDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileScreenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProfileScreens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProfileScreens
   * const profileScreen = await prisma.profileScreen.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileScreenUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileScreenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ProfileScreen.
   * @param {ProfileScreenUpsertArgs} args - Arguments to update or create a ProfileScreen.
   * @example
   * // Update or create a ProfileScreen
   * const profileScreen = await prisma.profileScreen.upsert({
   *   create: {
   *     // ... data to create a ProfileScreen
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProfileScreen we want to update
   *   }
   * })
   */
  upsert<T extends ProfileScreenUpsertArgs>(args: Prisma.SelectSubset<T, ProfileScreenUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileScreenClient<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProfileScreens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenCountArgs} args - Arguments to filter ProfileScreens to count.
   * @example
   * // Count the number of ProfileScreens
   * const count = await prisma.profileScreen.count({
   *   where: {
   *     // ... the filter for the ProfileScreens we want to count
   *   }
   * })
  **/
  count<T extends ProfileScreenCountArgs>(
    args?: Prisma.Subset<T, ProfileScreenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileScreenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProfileScreen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileScreenAggregateArgs>(args: Prisma.Subset<T, ProfileScreenAggregateArgs>): Prisma.PrismaPromise<GetProfileScreenAggregateType<T>>

  /**
   * Group by ProfileScreen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileScreenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileScreenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileScreenGroupByArgs['orderBy'] }
      : { orderBy?: ProfileScreenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileScreenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileScreenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProfileScreen model
 */
readonly fields: ProfileScreenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProfileScreen.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileScreenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  screen<T extends Prisma.ScreenDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ScreenDefaultArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProfileScreen model
 */
export interface ProfileScreenFieldRefs {
  readonly profile_id: Prisma.FieldRef<"ProfileScreen", 'String'>
  readonly screen_id: Prisma.FieldRef<"ProfileScreen", 'String'>
  readonly can_view: Prisma.FieldRef<"ProfileScreen", 'Boolean'>
  readonly can_create: Prisma.FieldRef<"ProfileScreen", 'Boolean'>
  readonly can_edit: Prisma.FieldRef<"ProfileScreen", 'Boolean'>
  readonly can_delete: Prisma.FieldRef<"ProfileScreen", 'Boolean'>
  readonly is_default: Prisma.FieldRef<"ProfileScreen", 'Boolean'>
}
    

// Custom InputTypes
/**
 * ProfileScreen findUnique
 */
export type ProfileScreenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter, which ProfileScreen to fetch.
   */
  where: Prisma.ProfileScreenWhereUniqueInput
}

/**
 * ProfileScreen findUniqueOrThrow
 */
export type ProfileScreenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter, which ProfileScreen to fetch.
   */
  where: Prisma.ProfileScreenWhereUniqueInput
}

/**
 * ProfileScreen findFirst
 */
export type ProfileScreenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter, which ProfileScreen to fetch.
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileScreens to fetch.
   */
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileScreens.
   */
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileScreens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileScreens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileScreens.
   */
  distinct?: Prisma.ProfileScreenScalarFieldEnum | Prisma.ProfileScreenScalarFieldEnum[]
}

/**
 * ProfileScreen findFirstOrThrow
 */
export type ProfileScreenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter, which ProfileScreen to fetch.
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileScreens to fetch.
   */
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileScreens.
   */
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileScreens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileScreens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileScreens.
   */
  distinct?: Prisma.ProfileScreenScalarFieldEnum | Prisma.ProfileScreenScalarFieldEnum[]
}

/**
 * ProfileScreen findMany
 */
export type ProfileScreenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter, which ProfileScreens to fetch.
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileScreens to fetch.
   */
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProfileScreens.
   */
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileScreens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileScreens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileScreens.
   */
  distinct?: Prisma.ProfileScreenScalarFieldEnum | Prisma.ProfileScreenScalarFieldEnum[]
}

/**
 * ProfileScreen create
 */
export type ProfileScreenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * The data needed to create a ProfileScreen.
   */
  data: Prisma.XOR<Prisma.ProfileScreenCreateInput, Prisma.ProfileScreenUncheckedCreateInput>
}

/**
 * ProfileScreen createMany
 */
export type ProfileScreenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProfileScreens.
   */
  data: Prisma.ProfileScreenCreateManyInput | Prisma.ProfileScreenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProfileScreen update
 */
export type ProfileScreenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * The data needed to update a ProfileScreen.
   */
  data: Prisma.XOR<Prisma.ProfileScreenUpdateInput, Prisma.ProfileScreenUncheckedUpdateInput>
  /**
   * Choose, which ProfileScreen to update.
   */
  where: Prisma.ProfileScreenWhereUniqueInput
}

/**
 * ProfileScreen updateMany
 */
export type ProfileScreenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProfileScreens.
   */
  data: Prisma.XOR<Prisma.ProfileScreenUpdateManyMutationInput, Prisma.ProfileScreenUncheckedUpdateManyInput>
  /**
   * Filter which ProfileScreens to update
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * Limit how many ProfileScreens to update.
   */
  limit?: number
}

/**
 * ProfileScreen upsert
 */
export type ProfileScreenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * The filter to search for the ProfileScreen to update in case it exists.
   */
  where: Prisma.ProfileScreenWhereUniqueInput
  /**
   * In case the ProfileScreen found by the `where` argument doesn't exist, create a new ProfileScreen with this data.
   */
  create: Prisma.XOR<Prisma.ProfileScreenCreateInput, Prisma.ProfileScreenUncheckedCreateInput>
  /**
   * In case the ProfileScreen was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileScreenUpdateInput, Prisma.ProfileScreenUncheckedUpdateInput>
}

/**
 * ProfileScreen delete
 */
export type ProfileScreenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  /**
   * Filter which ProfileScreen to delete.
   */
  where: Prisma.ProfileScreenWhereUniqueInput
}

/**
 * ProfileScreen deleteMany
 */
export type ProfileScreenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileScreens to delete
   */
  where?: Prisma.ProfileScreenWhereInput
  /**
   * Limit how many ProfileScreens to delete.
   */
  limit?: number
}

/**
 * ProfileScreen without action
 */
export type ProfileScreenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
}
