
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Profile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Profile
 * 
 */
export type ProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfilePayload>

export type AggregateProfile = {
  _count: ProfileCountAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

export type ProfileMinAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  description: string | null
  is_system: boolean | null
  is_default: boolean | null
  is_active: boolean | null
  created_at: Date | null
  default_screen_id: string | null
}

export type ProfileMaxAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  description: string | null
  is_system: boolean | null
  is_default: boolean | null
  is_active: boolean | null
  created_at: Date | null
  default_screen_id: string | null
}

export type ProfileCountAggregateOutputType = {
  id: number
  key: number
  name: number
  description: number
  is_system: number
  is_default: number
  is_active: number
  created_at: number
  default_screen_id: number
  _all: number
}


export type ProfileMinAggregateInputType = {
  id?: true
  key?: true
  name?: true
  description?: true
  is_system?: true
  is_default?: true
  is_active?: true
  created_at?: true
  default_screen_id?: true
}

export type ProfileMaxAggregateInputType = {
  id?: true
  key?: true
  name?: true
  description?: true
  is_system?: true
  is_default?: true
  is_active?: true
  created_at?: true
  default_screen_id?: true
}

export type ProfileCountAggregateInputType = {
  id?: true
  key?: true
  name?: true
  description?: true
  is_system?: true
  is_default?: true
  is_active?: true
  created_at?: true
  default_screen_id?: true
  _all?: true
}

export type ProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profile to aggregate.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Profiles
  **/
  _count?: true | ProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileMaxAggregateInputType
}

export type GetProfileAggregateType<T extends ProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateProfile[P]>
}




export type ProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithAggregationInput | Prisma.ProfileOrderByWithAggregationInput[]
  by: Prisma.ProfileScalarFieldEnum[] | Prisma.ProfileScalarFieldEnum
  having?: Prisma.ProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileCountAggregateInputType | true
  _min?: ProfileMinAggregateInputType
  _max?: ProfileMaxAggregateInputType
}

export type ProfileGroupByOutputType = {
  id: string
  key: string
  name: string
  description: string | null
  is_system: boolean
  is_default: boolean
  is_active: boolean
  created_at: Date
  default_screen_id: string | null
  _count: ProfileCountAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

export type GetProfileGroupByPayload<T extends ProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
      }
    >
  >



export type ProfileWhereInput = {
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  id?: Prisma.StringFilter<"Profile"> | string
  key?: Prisma.StringFilter<"Profile"> | string
  name?: Prisma.StringFilter<"Profile"> | string
  description?: Prisma.StringNullableFilter<"Profile"> | string | null
  is_system?: Prisma.BoolFilter<"Profile"> | boolean
  is_default?: Prisma.BoolFilter<"Profile"> | boolean
  is_active?: Prisma.BoolFilter<"Profile"> | boolean
  created_at?: Prisma.DateTimeFilter<"Profile"> | Date | string
  default_screen_id?: Prisma.StringNullableFilter<"Profile"> | string | null
  default_screen?: Prisma.XOR<Prisma.ScreenNullableScalarRelationFilter, Prisma.ScreenWhereInput> | null
  screens?: Prisma.ProfileScreenListRelationFilter
  permissions?: Prisma.ProfilePermissionListRelationFilter
  users?: Prisma.UserProfileListRelationFilter
}

export type ProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  default_screen_id?: Prisma.SortOrderInput | Prisma.SortOrder
  default_screen?: Prisma.ScreenOrderByWithRelationInput
  screens?: Prisma.ProfileScreenOrderByRelationAggregateInput
  permissions?: Prisma.ProfilePermissionOrderByRelationAggregateInput
  users?: Prisma.UserProfileOrderByRelationAggregateInput
  _relevance?: Prisma.ProfileOrderByRelevanceInput
}

export type ProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  name?: Prisma.StringFilter<"Profile"> | string
  description?: Prisma.StringNullableFilter<"Profile"> | string | null
  is_system?: Prisma.BoolFilter<"Profile"> | boolean
  is_default?: Prisma.BoolFilter<"Profile"> | boolean
  is_active?: Prisma.BoolFilter<"Profile"> | boolean
  created_at?: Prisma.DateTimeFilter<"Profile"> | Date | string
  default_screen_id?: Prisma.StringNullableFilter<"Profile"> | string | null
  default_screen?: Prisma.XOR<Prisma.ScreenNullableScalarRelationFilter, Prisma.ScreenWhereInput> | null
  screens?: Prisma.ProfileScreenListRelationFilter
  permissions?: Prisma.ProfilePermissionListRelationFilter
  users?: Prisma.UserProfileListRelationFilter
}, "id" | "key">

export type ProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  default_screen_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProfileCountOrderByAggregateInput
  _max?: Prisma.ProfileMaxOrderByAggregateInput
  _min?: Prisma.ProfileMinOrderByAggregateInput
}

export type ProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  key?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  name?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  is_system?: Prisma.BoolWithAggregatesFilter<"Profile"> | boolean
  is_default?: Prisma.BoolWithAggregatesFilter<"Profile"> | boolean
  is_active?: Prisma.BoolWithAggregatesFilter<"Profile"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Profile"> | Date | string
  default_screen_id?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
}

export type ProfileCreateInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen?: Prisma.ScreenCreateNestedOneWithoutDefault_forInput
  screens?: Prisma.ProfileScreenCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen_id?: string | null
  screens?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionUncheckedCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen?: Prisma.ScreenUpdateOneWithoutDefault_forNestedInput
  screens?: Prisma.ProfileScreenUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  screens?: Prisma.ProfileScreenUncheckedUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUncheckedUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateManyInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen_id?: string | null
}

export type ProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileListRelationFilter = {
  every?: Prisma.ProfileWhereInput
  some?: Prisma.ProfileWhereInput
  none?: Prisma.ProfileWhereInput
}

export type ProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProfileOrderByRelevanceInput = {
  fields: Prisma.ProfileOrderByRelevanceFieldEnum | Prisma.ProfileOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  default_screen_id?: Prisma.SortOrder
}

export type ProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  default_screen_id?: Prisma.SortOrder
}

export type ProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_default?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  default_screen_id?: Prisma.SortOrder
}

export type ProfileScalarRelationFilter = {
  is?: Prisma.ProfileWhereInput
  isNot?: Prisma.ProfileWhereInput
}

export type ProfileCreateNestedManyWithoutDefault_screenInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput> | Prisma.ProfileCreateWithoutDefault_screenInput[] | Prisma.ProfileUncheckedCreateWithoutDefault_screenInput[]
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutDefault_screenInput | Prisma.ProfileCreateOrConnectWithoutDefault_screenInput[]
  createMany?: Prisma.ProfileCreateManyDefault_screenInputEnvelope
  connect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
}

export type ProfileUncheckedCreateNestedManyWithoutDefault_screenInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput> | Prisma.ProfileCreateWithoutDefault_screenInput[] | Prisma.ProfileUncheckedCreateWithoutDefault_screenInput[]
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutDefault_screenInput | Prisma.ProfileCreateOrConnectWithoutDefault_screenInput[]
  createMany?: Prisma.ProfileCreateManyDefault_screenInputEnvelope
  connect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
}

export type ProfileUpdateManyWithoutDefault_screenNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput> | Prisma.ProfileCreateWithoutDefault_screenInput[] | Prisma.ProfileUncheckedCreateWithoutDefault_screenInput[]
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutDefault_screenInput | Prisma.ProfileCreateOrConnectWithoutDefault_screenInput[]
  upsert?: Prisma.ProfileUpsertWithWhereUniqueWithoutDefault_screenInput | Prisma.ProfileUpsertWithWhereUniqueWithoutDefault_screenInput[]
  createMany?: Prisma.ProfileCreateManyDefault_screenInputEnvelope
  set?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  disconnect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  delete?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  connect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  update?: Prisma.ProfileUpdateWithWhereUniqueWithoutDefault_screenInput | Prisma.ProfileUpdateWithWhereUniqueWithoutDefault_screenInput[]
  updateMany?: Prisma.ProfileUpdateManyWithWhereWithoutDefault_screenInput | Prisma.ProfileUpdateManyWithWhereWithoutDefault_screenInput[]
  deleteMany?: Prisma.ProfileScalarWhereInput | Prisma.ProfileScalarWhereInput[]
}

export type ProfileUncheckedUpdateManyWithoutDefault_screenNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput> | Prisma.ProfileCreateWithoutDefault_screenInput[] | Prisma.ProfileUncheckedCreateWithoutDefault_screenInput[]
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutDefault_screenInput | Prisma.ProfileCreateOrConnectWithoutDefault_screenInput[]
  upsert?: Prisma.ProfileUpsertWithWhereUniqueWithoutDefault_screenInput | Prisma.ProfileUpsertWithWhereUniqueWithoutDefault_screenInput[]
  createMany?: Prisma.ProfileCreateManyDefault_screenInputEnvelope
  set?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  disconnect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  delete?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  connect?: Prisma.ProfileWhereUniqueInput | Prisma.ProfileWhereUniqueInput[]
  update?: Prisma.ProfileUpdateWithWhereUniqueWithoutDefault_screenInput | Prisma.ProfileUpdateWithWhereUniqueWithoutDefault_screenInput[]
  updateMany?: Prisma.ProfileUpdateManyWithWhereWithoutDefault_screenInput | Prisma.ProfileUpdateManyWithWhereWithoutDefault_screenInput[]
  deleteMany?: Prisma.ProfileScalarWhereInput | Prisma.ProfileScalarWhereInput[]
}

export type ProfileCreateNestedOneWithoutScreensInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutScreensInput, Prisma.ProfileUncheckedCreateWithoutScreensInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutScreensInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutScreensNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutScreensInput, Prisma.ProfileUncheckedCreateWithoutScreensInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutScreensInput
  upsert?: Prisma.ProfileUpsertWithoutScreensInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutScreensInput, Prisma.ProfileUpdateWithoutScreensInput>, Prisma.ProfileUncheckedUpdateWithoutScreensInput>
}

export type ProfileCreateNestedOneWithoutPermissionsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutPermissionsInput, Prisma.ProfileUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutPermissionsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutPermissionsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutPermissionsInput, Prisma.ProfileUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutPermissionsInput
  upsert?: Prisma.ProfileUpsertWithoutPermissionsInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutPermissionsInput, Prisma.ProfileUpdateWithoutPermissionsInput>, Prisma.ProfileUncheckedUpdateWithoutPermissionsInput>
}

export type ProfileCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUsersInput, Prisma.ProfileUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUsersInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUsersInput, Prisma.ProfileUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUsersInput
  upsert?: Prisma.ProfileUpsertWithoutUsersInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutUsersInput, Prisma.ProfileUpdateWithoutUsersInput>, Prisma.ProfileUncheckedUpdateWithoutUsersInput>
}

export type ProfileCreateWithoutDefault_screenInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  screens?: Prisma.ProfileScreenCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutDefault_screenInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  screens?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionUncheckedCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutDefault_screenInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput>
}

export type ProfileCreateManyDefault_screenInputEnvelope = {
  data: Prisma.ProfileCreateManyDefault_screenInput | Prisma.ProfileCreateManyDefault_screenInput[]
  skipDuplicates?: boolean
}

export type ProfileUpsertWithWhereUniqueWithoutDefault_screenInput = {
  where: Prisma.ProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutDefault_screenInput, Prisma.ProfileUncheckedUpdateWithoutDefault_screenInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutDefault_screenInput, Prisma.ProfileUncheckedCreateWithoutDefault_screenInput>
}

export type ProfileUpdateWithWhereUniqueWithoutDefault_screenInput = {
  where: Prisma.ProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutDefault_screenInput, Prisma.ProfileUncheckedUpdateWithoutDefault_screenInput>
}

export type ProfileUpdateManyWithWhereWithoutDefault_screenInput = {
  where: Prisma.ProfileScalarWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyWithoutDefault_screenInput>
}

export type ProfileScalarWhereInput = {
  AND?: Prisma.ProfileScalarWhereInput | Prisma.ProfileScalarWhereInput[]
  OR?: Prisma.ProfileScalarWhereInput[]
  NOT?: Prisma.ProfileScalarWhereInput | Prisma.ProfileScalarWhereInput[]
  id?: Prisma.StringFilter<"Profile"> | string
  key?: Prisma.StringFilter<"Profile"> | string
  name?: Prisma.StringFilter<"Profile"> | string
  description?: Prisma.StringNullableFilter<"Profile"> | string | null
  is_system?: Prisma.BoolFilter<"Profile"> | boolean
  is_default?: Prisma.BoolFilter<"Profile"> | boolean
  is_active?: Prisma.BoolFilter<"Profile"> | boolean
  created_at?: Prisma.DateTimeFilter<"Profile"> | Date | string
  default_screen_id?: Prisma.StringNullableFilter<"Profile"> | string | null
}

export type ProfileCreateWithoutScreensInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen?: Prisma.ScreenCreateNestedOneWithoutDefault_forInput
  permissions?: Prisma.ProfilePermissionCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutScreensInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen_id?: string | null
  permissions?: Prisma.ProfilePermissionUncheckedCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutScreensInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutScreensInput, Prisma.ProfileUncheckedCreateWithoutScreensInput>
}

export type ProfileUpsertWithoutScreensInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutScreensInput, Prisma.ProfileUncheckedUpdateWithoutScreensInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutScreensInput, Prisma.ProfileUncheckedCreateWithoutScreensInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutScreensInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutScreensInput, Prisma.ProfileUncheckedUpdateWithoutScreensInput>
}

export type ProfileUpdateWithoutScreensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen?: Prisma.ScreenUpdateOneWithoutDefault_forNestedInput
  permissions?: Prisma.ProfilePermissionUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutScreensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.ProfilePermissionUncheckedUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateWithoutPermissionsInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen?: Prisma.ScreenCreateNestedOneWithoutDefault_forInput
  screens?: Prisma.ProfileScreenCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutPermissionsInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen_id?: string | null
  screens?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutProfileInput
  users?: Prisma.UserProfileUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutPermissionsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutPermissionsInput, Prisma.ProfileUncheckedCreateWithoutPermissionsInput>
}

export type ProfileUpsertWithoutPermissionsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutPermissionsInput, Prisma.ProfileUncheckedUpdateWithoutPermissionsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutPermissionsInput, Prisma.ProfileUncheckedCreateWithoutPermissionsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutPermissionsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutPermissionsInput, Prisma.ProfileUncheckedUpdateWithoutPermissionsInput>
}

export type ProfileUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen?: Prisma.ScreenUpdateOneWithoutDefault_forNestedInput
  screens?: Prisma.ProfileScreenUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  screens?: Prisma.ProfileScreenUncheckedUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateWithoutUsersInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen?: Prisma.ScreenCreateNestedOneWithoutDefault_forInput
  screens?: Prisma.ProfileScreenCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutUsersInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
  default_screen_id?: string | null
  screens?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutProfileInput
  permissions?: Prisma.ProfilePermissionUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutUsersInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutUsersInput, Prisma.ProfileUncheckedCreateWithoutUsersInput>
}

export type ProfileUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutUsersInput, Prisma.ProfileUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutUsersInput, Prisma.ProfileUncheckedCreateWithoutUsersInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutUsersInput, Prisma.ProfileUncheckedUpdateWithoutUsersInput>
}

export type ProfileUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen?: Prisma.ScreenUpdateOneWithoutDefault_forNestedInput
  screens?: Prisma.ProfileScreenUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  default_screen_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  screens?: Prisma.ProfileScreenUncheckedUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateManyDefault_screenInput = {
  id?: string
  key: string
  name: string
  description?: string | null
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: Date | string
}

export type ProfileUpdateWithoutDefault_screenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screens?: Prisma.ProfileScreenUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutDefault_screenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screens?: Prisma.ProfileScreenUncheckedUpdateManyWithoutProfileNestedInput
  permissions?: Prisma.ProfilePermissionUncheckedUpdateManyWithoutProfileNestedInput
  users?: Prisma.UserProfileUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateManyWithoutDefault_screenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_default?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProfileCountOutputType
 */

export type ProfileCountOutputType = {
  screens: number
  permissions: number
  users: number
}

export type ProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  screens?: boolean | ProfileCountOutputTypeCountScreensArgs
  permissions?: boolean | ProfileCountOutputTypeCountPermissionsArgs
  users?: boolean | ProfileCountOutputTypeCountUsersArgs
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileCountOutputType
   */
  select?: Prisma.ProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountScreensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileScreenWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountPermissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfilePermissionWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserProfileWhereInput
}


export type ProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  description?: boolean
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: boolean
  default_screen_id?: boolean
  default_screen?: boolean | Prisma.Profile$default_screenArgs<ExtArgs>
  screens?: boolean | Prisma.Profile$screensArgs<ExtArgs>
  permissions?: boolean | Prisma.Profile$permissionsArgs<ExtArgs>
  users?: boolean | Prisma.Profile$usersArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profile"]>



export type ProfileSelectScalar = {
  id?: boolean
  key?: boolean
  name?: boolean
  description?: boolean
  is_system?: boolean
  is_default?: boolean
  is_active?: boolean
  created_at?: boolean
  default_screen_id?: boolean
}

export type ProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "name" | "description" | "is_system" | "is_default" | "is_active" | "created_at" | "default_screen_id", ExtArgs["result"]["profile"]>
export type ProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  default_screen?: boolean | Prisma.Profile$default_screenArgs<ExtArgs>
  screens?: boolean | Prisma.Profile$screensArgs<ExtArgs>
  permissions?: boolean | Prisma.Profile$permissionsArgs<ExtArgs>
  users?: boolean | Prisma.Profile$usersArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Profile"
  objects: {
    default_screen: Prisma.$ScreenPayload<ExtArgs> | null
    screens: Prisma.$ProfileScreenPayload<ExtArgs>[]
    permissions: Prisma.$ProfilePermissionPayload<ExtArgs>[]
    users: Prisma.$UserProfilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    name: string
    description: string | null
    is_system: boolean
    is_default: boolean
    is_active: boolean
    created_at: Date
    default_screen_id: string | null
  }, ExtArgs["result"]["profile"]>
  composites: {}
}

export type ProfileGetPayload<S extends boolean | null | undefined | ProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfilePayload, S>

export type ProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileCountAggregateInputType | true
  }

export interface ProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Profile'], meta: { name: 'Profile' } }
  /**
   * Find zero or one Profile that matches the filter.
   * @param {ProfileFindUniqueArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Profile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileFindUniqueOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Profiles
   * const profiles = await prisma.profile.findMany()
   * 
   * // Get first 10 Profiles
   * const profiles = await prisma.profile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profileWithIdOnly = await prisma.profile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfileFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Profile.
   * @param {ProfileCreateArgs} args - Arguments to create a Profile.
   * @example
   * // Create one Profile
   * const Profile = await prisma.profile.create({
   *   data: {
   *     // ... data to create a Profile
   *   }
   * })
   * 
   */
  create<T extends ProfileCreateArgs>(args: Prisma.SelectSubset<T, ProfileCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Profiles.
   * @param {ProfileCreateManyArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profile = await prisma.profile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Profile.
   * @param {ProfileDeleteArgs} args - Arguments to delete one Profile.
   * @example
   * // Delete one Profile
   * const Profile = await prisma.profile.delete({
   *   where: {
   *     // ... filter to delete one Profile
   *   }
   * })
   * 
   */
  delete<T extends ProfileDeleteArgs>(args: Prisma.SelectSubset<T, ProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Profile.
   * @param {ProfileUpdateArgs} args - Arguments to update one Profile.
   * @example
   * // Update one Profile
   * const profile = await prisma.profile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileUpdateArgs>(args: Prisma.SelectSubset<T, ProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Profiles.
   * @param {ProfileDeleteManyArgs} args - Arguments to filter Profiles to delete.
   * @example
   * // Delete a few Profiles
   * const { count } = await prisma.profile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Profiles
   * const profile = await prisma.profile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Profile.
   * @param {ProfileUpsertArgs} args - Arguments to update or create a Profile.
   * @example
   * // Update or create a Profile
   * const profile = await prisma.profile.upsert({
   *   create: {
   *     // ... data to create a Profile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Profile we want to update
   *   }
   * })
   */
  upsert<T extends ProfileUpsertArgs>(args: Prisma.SelectSubset<T, ProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileCountArgs} args - Arguments to filter Profiles to count.
   * @example
   * // Count the number of Profiles
   * const count = await prisma.profile.count({
   *   where: {
   *     // ... the filter for the Profiles we want to count
   *   }
   * })
  **/
  count<T extends ProfileCountArgs>(
    args?: Prisma.Subset<T, ProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileAggregateArgs>(args: Prisma.Subset<T, ProfileAggregateArgs>): Prisma.PrismaPromise<GetProfileAggregateType<T>>

  /**
   * Group by Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileGroupByArgs['orderBy'] }
      : { orderBy?: ProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Profile model
 */
readonly fields: ProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Profile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  default_screen<T extends Prisma.Profile$default_screenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$default_screenArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  screens<T extends Prisma.Profile$screensArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$screensArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  permissions<T extends Prisma.Profile$permissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$permissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  users<T extends Prisma.Profile$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Profile model
 */
export interface ProfileFieldRefs {
  readonly id: Prisma.FieldRef<"Profile", 'String'>
  readonly key: Prisma.FieldRef<"Profile", 'String'>
  readonly name: Prisma.FieldRef<"Profile", 'String'>
  readonly description: Prisma.FieldRef<"Profile", 'String'>
  readonly is_system: Prisma.FieldRef<"Profile", 'Boolean'>
  readonly is_default: Prisma.FieldRef<"Profile", 'Boolean'>
  readonly is_active: Prisma.FieldRef<"Profile", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"Profile", 'DateTime'>
  readonly default_screen_id: Prisma.FieldRef<"Profile", 'String'>
}
    

// Custom InputTypes
/**
 * Profile findUnique
 */
export type ProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findUniqueOrThrow
 */
export type ProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findFirst
 */
export type ProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findFirstOrThrow
 */
export type ProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findMany
 */
export type ProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile create
 */
export type ProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
}

/**
 * Profile createMany
 */
export type ProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfileCreateManyInput | Prisma.ProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profile update
 */
export type ProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
  /**
   * Choose, which Profile to update.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile updateMany
 */
export type ProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
}

/**
 * Profile upsert
 */
export type ProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the Profile to update in case it exists.
   */
  where: Prisma.ProfileWhereUniqueInput
  /**
   * In case the Profile found by the `where` argument doesn't exist, create a new Profile with this data.
   */
  create: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
  /**
   * In case the Profile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
}

/**
 * Profile delete
 */
export type ProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter which Profile to delete.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile deleteMany
 */
export type ProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profiles to delete
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to delete.
   */
  limit?: number
}

/**
 * Profile.default_screen
 */
export type Profile$default_screenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  where?: Prisma.ScreenWhereInput
}

/**
 * Profile.screens
 */
export type Profile$screensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  where?: Prisma.ProfileScreenWhereInput
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfileScreenScalarFieldEnum | Prisma.ProfileScreenScalarFieldEnum[]
}

/**
 * Profile.permissions
 */
export type Profile$permissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfilePermission
   */
  select?: Prisma.ProfilePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfilePermission
   */
  omit?: Prisma.ProfilePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilePermissionInclude<ExtArgs> | null
  where?: Prisma.ProfilePermissionWhereInput
  orderBy?: Prisma.ProfilePermissionOrderByWithRelationInput | Prisma.ProfilePermissionOrderByWithRelationInput[]
  cursor?: Prisma.ProfilePermissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfilePermissionScalarFieldEnum | Prisma.ProfilePermissionScalarFieldEnum[]
}

/**
 * Profile.users
 */
export type Profile$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  where?: Prisma.UserProfileWhereInput
  orderBy?: Prisma.UserProfileOrderByWithRelationInput | Prisma.UserProfileOrderByWithRelationInput[]
  cursor?: Prisma.UserProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserProfileScalarFieldEnum | Prisma.UserProfileScalarFieldEnum[]
}

/**
 * Profile without action
 */
export type ProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
}
