
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Screen` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Screen
 * 
 */
export type ScreenModel = runtime.Types.Result.DefaultSelection<Prisma.$ScreenPayload>

export type AggregateScreen = {
  _count: ScreenCountAggregateOutputType | null
  _avg: ScreenAvgAggregateOutputType | null
  _sum: ScreenSumAggregateOutputType | null
  _min: ScreenMinAggregateOutputType | null
  _max: ScreenMaxAggregateOutputType | null
}

export type ScreenAvgAggregateOutputType = {
  order: number | null
}

export type ScreenSumAggregateOutputType = {
  order: number | null
}

export type ScreenMinAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  path: string | null
  description: string | null
  order: number | null
  is_system: boolean | null
  is_active: boolean | null
  is_enabled: boolean | null
  module_id: string | null
}

export type ScreenMaxAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  path: string | null
  description: string | null
  order: number | null
  is_system: boolean | null
  is_active: boolean | null
  is_enabled: boolean | null
  module_id: string | null
}

export type ScreenCountAggregateOutputType = {
  id: number
  key: number
  name: number
  path: number
  description: number
  order: number
  is_system: number
  is_active: number
  is_enabled: number
  module_id: number
  _all: number
}


export type ScreenAvgAggregateInputType = {
  order?: true
}

export type ScreenSumAggregateInputType = {
  order?: true
}

export type ScreenMinAggregateInputType = {
  id?: true
  key?: true
  name?: true
  path?: true
  description?: true
  order?: true
  is_system?: true
  is_active?: true
  is_enabled?: true
  module_id?: true
}

export type ScreenMaxAggregateInputType = {
  id?: true
  key?: true
  name?: true
  path?: true
  description?: true
  order?: true
  is_system?: true
  is_active?: true
  is_enabled?: true
  module_id?: true
}

export type ScreenCountAggregateInputType = {
  id?: true
  key?: true
  name?: true
  path?: true
  description?: true
  order?: true
  is_system?: true
  is_active?: true
  is_enabled?: true
  module_id?: true
  _all?: true
}

export type ScreenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Screen to aggregate.
   */
  where?: Prisma.ScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Screens to fetch.
   */
  orderBy?: Prisma.ScreenOrderByWithRelationInput | Prisma.ScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Screens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Screens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Screens
  **/
  _count?: true | ScreenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ScreenAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ScreenSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ScreenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ScreenMaxAggregateInputType
}

export type GetScreenAggregateType<T extends ScreenAggregateArgs> = {
      [P in keyof T & keyof AggregateScreen]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateScreen[P]>
    : Prisma.GetScalarType<T[P], AggregateScreen[P]>
}




export type ScreenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScreenWhereInput
  orderBy?: Prisma.ScreenOrderByWithAggregationInput | Prisma.ScreenOrderByWithAggregationInput[]
  by: Prisma.ScreenScalarFieldEnum[] | Prisma.ScreenScalarFieldEnum
  having?: Prisma.ScreenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ScreenCountAggregateInputType | true
  _avg?: ScreenAvgAggregateInputType
  _sum?: ScreenSumAggregateInputType
  _min?: ScreenMinAggregateInputType
  _max?: ScreenMaxAggregateInputType
}

export type ScreenGroupByOutputType = {
  id: string
  key: string
  name: string
  path: string | null
  description: string | null
  order: number
  is_system: boolean
  is_active: boolean
  is_enabled: boolean
  module_id: string
  _count: ScreenCountAggregateOutputType | null
  _avg: ScreenAvgAggregateOutputType | null
  _sum: ScreenSumAggregateOutputType | null
  _min: ScreenMinAggregateOutputType | null
  _max: ScreenMaxAggregateOutputType | null
}

export type GetScreenGroupByPayload<T extends ScreenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ScreenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ScreenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ScreenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ScreenGroupByOutputType[P]>
      }
    >
  >



export type ScreenWhereInput = {
  AND?: Prisma.ScreenWhereInput | Prisma.ScreenWhereInput[]
  OR?: Prisma.ScreenWhereInput[]
  NOT?: Prisma.ScreenWhereInput | Prisma.ScreenWhereInput[]
  id?: Prisma.StringFilter<"Screen"> | string
  key?: Prisma.StringFilter<"Screen"> | string
  name?: Prisma.StringFilter<"Screen"> | string
  path?: Prisma.StringNullableFilter<"Screen"> | string | null
  description?: Prisma.StringNullableFilter<"Screen"> | string | null
  order?: Prisma.IntFilter<"Screen"> | number
  is_system?: Prisma.BoolFilter<"Screen"> | boolean
  is_active?: Prisma.BoolFilter<"Screen"> | boolean
  is_enabled?: Prisma.BoolFilter<"Screen"> | boolean
  module_id?: Prisma.StringFilter<"Screen"> | string
  module?: Prisma.XOR<Prisma.ModuleScalarRelationFilter, Prisma.ModuleWhereInput>
  members?: Prisma.ProfileScreenListRelationFilter
  permissions?: Prisma.PermissionListRelationFilter
  default_for?: Prisma.ProfileListRelationFilter
}

export type ScreenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_enabled?: Prisma.SortOrder
  module_id?: Prisma.SortOrder
  module?: Prisma.ModuleOrderByWithRelationInput
  members?: Prisma.ProfileScreenOrderByRelationAggregateInput
  permissions?: Prisma.PermissionOrderByRelationAggregateInput
  default_for?: Prisma.ProfileOrderByRelationAggregateInput
  _relevance?: Prisma.ScreenOrderByRelevanceInput
}

export type ScreenWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.ScreenWhereInput | Prisma.ScreenWhereInput[]
  OR?: Prisma.ScreenWhereInput[]
  NOT?: Prisma.ScreenWhereInput | Prisma.ScreenWhereInput[]
  name?: Prisma.StringFilter<"Screen"> | string
  path?: Prisma.StringNullableFilter<"Screen"> | string | null
  description?: Prisma.StringNullableFilter<"Screen"> | string | null
  order?: Prisma.IntFilter<"Screen"> | number
  is_system?: Prisma.BoolFilter<"Screen"> | boolean
  is_active?: Prisma.BoolFilter<"Screen"> | boolean
  is_enabled?: Prisma.BoolFilter<"Screen"> | boolean
  module_id?: Prisma.StringFilter<"Screen"> | string
  module?: Prisma.XOR<Prisma.ModuleScalarRelationFilter, Prisma.ModuleWhereInput>
  members?: Prisma.ProfileScreenListRelationFilter
  permissions?: Prisma.PermissionListRelationFilter
  default_for?: Prisma.ProfileListRelationFilter
}, "id" | "key">

export type ScreenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_enabled?: Prisma.SortOrder
  module_id?: Prisma.SortOrder
  _count?: Prisma.ScreenCountOrderByAggregateInput
  _avg?: Prisma.ScreenAvgOrderByAggregateInput
  _max?: Prisma.ScreenMaxOrderByAggregateInput
  _min?: Prisma.ScreenMinOrderByAggregateInput
  _sum?: Prisma.ScreenSumOrderByAggregateInput
}

export type ScreenScalarWhereWithAggregatesInput = {
  AND?: Prisma.ScreenScalarWhereWithAggregatesInput | Prisma.ScreenScalarWhereWithAggregatesInput[]
  OR?: Prisma.ScreenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ScreenScalarWhereWithAggregatesInput | Prisma.ScreenScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Screen"> | string
  key?: Prisma.StringWithAggregatesFilter<"Screen"> | string
  name?: Prisma.StringWithAggregatesFilter<"Screen"> | string
  path?: Prisma.StringNullableWithAggregatesFilter<"Screen"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Screen"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"Screen"> | number
  is_system?: Prisma.BoolWithAggregatesFilter<"Screen"> | boolean
  is_active?: Prisma.BoolWithAggregatesFilter<"Screen"> | boolean
  is_enabled?: Prisma.BoolWithAggregatesFilter<"Screen"> | boolean
  module_id?: Prisma.StringWithAggregatesFilter<"Screen"> | string
}

export type ScreenCreateInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module: Prisma.ModuleCreateNestedOneWithoutScreensInput
  members?: Prisma.ProfileScreenCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileCreateNestedManyWithoutDefault_screenInput
}

export type ScreenUncheckedCreateInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id: string
  members?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionUncheckedCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileUncheckedCreateNestedManyWithoutDefault_screenInput
}

export type ScreenUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module?: Prisma.ModuleUpdateOneRequiredWithoutScreensNestedInput
  members?: Prisma.ProfileScreenUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module_id?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.ProfileScreenUncheckedUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUncheckedUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUncheckedUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenCreateManyInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id: string
}

export type ScreenUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ScreenUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ScreenListRelationFilter = {
  every?: Prisma.ScreenWhereInput
  some?: Prisma.ScreenWhereInput
  none?: Prisma.ScreenWhereInput
}

export type ScreenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ScreenOrderByRelevanceInput = {
  fields: Prisma.ScreenOrderByRelevanceFieldEnum | Prisma.ScreenOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ScreenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_enabled?: Prisma.SortOrder
  module_id?: Prisma.SortOrder
}

export type ScreenAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type ScreenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_enabled?: Prisma.SortOrder
  module_id?: Prisma.SortOrder
}

export type ScreenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_system?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_enabled?: Prisma.SortOrder
  module_id?: Prisma.SortOrder
}

export type ScreenSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type ScreenNullableScalarRelationFilter = {
  is?: Prisma.ScreenWhereInput | null
  isNot?: Prisma.ScreenWhereInput | null
}

export type ScreenScalarRelationFilter = {
  is?: Prisma.ScreenWhereInput
  isNot?: Prisma.ScreenWhereInput
}

export type ScreenCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput> | Prisma.ScreenCreateWithoutModuleInput[] | Prisma.ScreenUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutModuleInput | Prisma.ScreenCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.ScreenCreateManyModuleInputEnvelope
  connect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
}

export type ScreenUncheckedCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput> | Prisma.ScreenCreateWithoutModuleInput[] | Prisma.ScreenUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutModuleInput | Prisma.ScreenCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.ScreenCreateManyModuleInputEnvelope
  connect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
}

export type ScreenUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput> | Prisma.ScreenCreateWithoutModuleInput[] | Prisma.ScreenUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutModuleInput | Prisma.ScreenCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.ScreenUpsertWithWhereUniqueWithoutModuleInput | Prisma.ScreenUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.ScreenCreateManyModuleInputEnvelope
  set?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  disconnect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  delete?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  connect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  update?: Prisma.ScreenUpdateWithWhereUniqueWithoutModuleInput | Prisma.ScreenUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.ScreenUpdateManyWithWhereWithoutModuleInput | Prisma.ScreenUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.ScreenScalarWhereInput | Prisma.ScreenScalarWhereInput[]
}

export type ScreenUncheckedUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput> | Prisma.ScreenCreateWithoutModuleInput[] | Prisma.ScreenUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutModuleInput | Prisma.ScreenCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.ScreenUpsertWithWhereUniqueWithoutModuleInput | Prisma.ScreenUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.ScreenCreateManyModuleInputEnvelope
  set?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  disconnect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  delete?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  connect?: Prisma.ScreenWhereUniqueInput | Prisma.ScreenWhereUniqueInput[]
  update?: Prisma.ScreenUpdateWithWhereUniqueWithoutModuleInput | Prisma.ScreenUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.ScreenUpdateManyWithWhereWithoutModuleInput | Prisma.ScreenUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.ScreenScalarWhereInput | Prisma.ScreenScalarWhereInput[]
}

export type ScreenCreateNestedOneWithoutDefault_forInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutDefault_forInput, Prisma.ScreenUncheckedCreateWithoutDefault_forInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutDefault_forInput
  connect?: Prisma.ScreenWhereUniqueInput
}

export type ScreenUpdateOneWithoutDefault_forNestedInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutDefault_forInput, Prisma.ScreenUncheckedCreateWithoutDefault_forInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutDefault_forInput
  upsert?: Prisma.ScreenUpsertWithoutDefault_forInput
  disconnect?: Prisma.ScreenWhereInput | boolean
  delete?: Prisma.ScreenWhereInput | boolean
  connect?: Prisma.ScreenWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ScreenUpdateToOneWithWhereWithoutDefault_forInput, Prisma.ScreenUpdateWithoutDefault_forInput>, Prisma.ScreenUncheckedUpdateWithoutDefault_forInput>
}

export type ScreenCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutMembersInput, Prisma.ScreenUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutMembersInput
  connect?: Prisma.ScreenWhereUniqueInput
}

export type ScreenUpdateOneRequiredWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutMembersInput, Prisma.ScreenUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutMembersInput
  upsert?: Prisma.ScreenUpsertWithoutMembersInput
  connect?: Prisma.ScreenWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ScreenUpdateToOneWithWhereWithoutMembersInput, Prisma.ScreenUpdateWithoutMembersInput>, Prisma.ScreenUncheckedUpdateWithoutMembersInput>
}

export type ScreenCreateNestedOneWithoutPermissionsInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutPermissionsInput, Prisma.ScreenUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutPermissionsInput
  connect?: Prisma.ScreenWhereUniqueInput
}

export type ScreenUpdateOneRequiredWithoutPermissionsNestedInput = {
  create?: Prisma.XOR<Prisma.ScreenCreateWithoutPermissionsInput, Prisma.ScreenUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.ScreenCreateOrConnectWithoutPermissionsInput
  upsert?: Prisma.ScreenUpsertWithoutPermissionsInput
  connect?: Prisma.ScreenWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ScreenUpdateToOneWithWhereWithoutPermissionsInput, Prisma.ScreenUpdateWithoutPermissionsInput>, Prisma.ScreenUncheckedUpdateWithoutPermissionsInput>
}

export type ScreenCreateWithoutModuleInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  members?: Prisma.ProfileScreenCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileCreateNestedManyWithoutDefault_screenInput
}

export type ScreenUncheckedCreateWithoutModuleInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  members?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionUncheckedCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileUncheckedCreateNestedManyWithoutDefault_screenInput
}

export type ScreenCreateOrConnectWithoutModuleInput = {
  where: Prisma.ScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput>
}

export type ScreenCreateManyModuleInputEnvelope = {
  data: Prisma.ScreenCreateManyModuleInput | Prisma.ScreenCreateManyModuleInput[]
  skipDuplicates?: boolean
}

export type ScreenUpsertWithWhereUniqueWithoutModuleInput = {
  where: Prisma.ScreenWhereUniqueInput
  update: Prisma.XOR<Prisma.ScreenUpdateWithoutModuleInput, Prisma.ScreenUncheckedUpdateWithoutModuleInput>
  create: Prisma.XOR<Prisma.ScreenCreateWithoutModuleInput, Prisma.ScreenUncheckedCreateWithoutModuleInput>
}

export type ScreenUpdateWithWhereUniqueWithoutModuleInput = {
  where: Prisma.ScreenWhereUniqueInput
  data: Prisma.XOR<Prisma.ScreenUpdateWithoutModuleInput, Prisma.ScreenUncheckedUpdateWithoutModuleInput>
}

export type ScreenUpdateManyWithWhereWithoutModuleInput = {
  where: Prisma.ScreenScalarWhereInput
  data: Prisma.XOR<Prisma.ScreenUpdateManyMutationInput, Prisma.ScreenUncheckedUpdateManyWithoutModuleInput>
}

export type ScreenScalarWhereInput = {
  AND?: Prisma.ScreenScalarWhereInput | Prisma.ScreenScalarWhereInput[]
  OR?: Prisma.ScreenScalarWhereInput[]
  NOT?: Prisma.ScreenScalarWhereInput | Prisma.ScreenScalarWhereInput[]
  id?: Prisma.StringFilter<"Screen"> | string
  key?: Prisma.StringFilter<"Screen"> | string
  name?: Prisma.StringFilter<"Screen"> | string
  path?: Prisma.StringNullableFilter<"Screen"> | string | null
  description?: Prisma.StringNullableFilter<"Screen"> | string | null
  order?: Prisma.IntFilter<"Screen"> | number
  is_system?: Prisma.BoolFilter<"Screen"> | boolean
  is_active?: Prisma.BoolFilter<"Screen"> | boolean
  is_enabled?: Prisma.BoolFilter<"Screen"> | boolean
  module_id?: Prisma.StringFilter<"Screen"> | string
}

export type ScreenCreateWithoutDefault_forInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module: Prisma.ModuleCreateNestedOneWithoutScreensInput
  members?: Prisma.ProfileScreenCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionCreateNestedManyWithoutScreenInput
}

export type ScreenUncheckedCreateWithoutDefault_forInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id: string
  members?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutScreenInput
  permissions?: Prisma.PermissionUncheckedCreateNestedManyWithoutScreenInput
}

export type ScreenCreateOrConnectWithoutDefault_forInput = {
  where: Prisma.ScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ScreenCreateWithoutDefault_forInput, Prisma.ScreenUncheckedCreateWithoutDefault_forInput>
}

export type ScreenUpsertWithoutDefault_forInput = {
  update: Prisma.XOR<Prisma.ScreenUpdateWithoutDefault_forInput, Prisma.ScreenUncheckedUpdateWithoutDefault_forInput>
  create: Prisma.XOR<Prisma.ScreenCreateWithoutDefault_forInput, Prisma.ScreenUncheckedCreateWithoutDefault_forInput>
  where?: Prisma.ScreenWhereInput
}

export type ScreenUpdateToOneWithWhereWithoutDefault_forInput = {
  where?: Prisma.ScreenWhereInput
  data: Prisma.XOR<Prisma.ScreenUpdateWithoutDefault_forInput, Prisma.ScreenUncheckedUpdateWithoutDefault_forInput>
}

export type ScreenUpdateWithoutDefault_forInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module?: Prisma.ModuleUpdateOneRequiredWithoutScreensNestedInput
  members?: Prisma.ProfileScreenUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUpdateManyWithoutScreenNestedInput
}

export type ScreenUncheckedUpdateWithoutDefault_forInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module_id?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.ProfileScreenUncheckedUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUncheckedUpdateManyWithoutScreenNestedInput
}

export type ScreenCreateWithoutMembersInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module: Prisma.ModuleCreateNestedOneWithoutScreensInput
  permissions?: Prisma.PermissionCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileCreateNestedManyWithoutDefault_screenInput
}

export type ScreenUncheckedCreateWithoutMembersInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id: string
  permissions?: Prisma.PermissionUncheckedCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileUncheckedCreateNestedManyWithoutDefault_screenInput
}

export type ScreenCreateOrConnectWithoutMembersInput = {
  where: Prisma.ScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ScreenCreateWithoutMembersInput, Prisma.ScreenUncheckedCreateWithoutMembersInput>
}

export type ScreenUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.ScreenUpdateWithoutMembersInput, Prisma.ScreenUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.ScreenCreateWithoutMembersInput, Prisma.ScreenUncheckedCreateWithoutMembersInput>
  where?: Prisma.ScreenWhereInput
}

export type ScreenUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.ScreenWhereInput
  data: Prisma.XOR<Prisma.ScreenUpdateWithoutMembersInput, Prisma.ScreenUncheckedUpdateWithoutMembersInput>
}

export type ScreenUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module?: Prisma.ModuleUpdateOneRequiredWithoutScreensNestedInput
  permissions?: Prisma.PermissionUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module_id?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.PermissionUncheckedUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUncheckedUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenCreateWithoutPermissionsInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module: Prisma.ModuleCreateNestedOneWithoutScreensInput
  members?: Prisma.ProfileScreenCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileCreateNestedManyWithoutDefault_screenInput
}

export type ScreenUncheckedCreateWithoutPermissionsInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id: string
  members?: Prisma.ProfileScreenUncheckedCreateNestedManyWithoutScreenInput
  default_for?: Prisma.ProfileUncheckedCreateNestedManyWithoutDefault_screenInput
}

export type ScreenCreateOrConnectWithoutPermissionsInput = {
  where: Prisma.ScreenWhereUniqueInput
  create: Prisma.XOR<Prisma.ScreenCreateWithoutPermissionsInput, Prisma.ScreenUncheckedCreateWithoutPermissionsInput>
}

export type ScreenUpsertWithoutPermissionsInput = {
  update: Prisma.XOR<Prisma.ScreenUpdateWithoutPermissionsInput, Prisma.ScreenUncheckedUpdateWithoutPermissionsInput>
  create: Prisma.XOR<Prisma.ScreenCreateWithoutPermissionsInput, Prisma.ScreenUncheckedCreateWithoutPermissionsInput>
  where?: Prisma.ScreenWhereInput
}

export type ScreenUpdateToOneWithWhereWithoutPermissionsInput = {
  where?: Prisma.ScreenWhereInput
  data: Prisma.XOR<Prisma.ScreenUpdateWithoutPermissionsInput, Prisma.ScreenUncheckedUpdateWithoutPermissionsInput>
}

export type ScreenUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module?: Prisma.ModuleUpdateOneRequiredWithoutScreensNestedInput
  members?: Prisma.ProfileScreenUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenUncheckedUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  module_id?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.ProfileScreenUncheckedUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUncheckedUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenCreateManyModuleInput = {
  id?: string
  key: string
  name: string
  path?: string | null
  description?: string | null
  order?: number
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
}

export type ScreenUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  members?: Prisma.ProfileScreenUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenUncheckedUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  members?: Prisma.ProfileScreenUncheckedUpdateManyWithoutScreenNestedInput
  permissions?: Prisma.PermissionUncheckedUpdateManyWithoutScreenNestedInput
  default_for?: Prisma.ProfileUncheckedUpdateManyWithoutDefault_screenNestedInput
}

export type ScreenUncheckedUpdateManyWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_system?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type ScreenCountOutputType
 */

export type ScreenCountOutputType = {
  members: number
  permissions: number
  default_for: number
}

export type ScreenCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | ScreenCountOutputTypeCountMembersArgs
  permissions?: boolean | ScreenCountOutputTypeCountPermissionsArgs
  default_for?: boolean | ScreenCountOutputTypeCountDefault_forArgs
}

/**
 * ScreenCountOutputType without action
 */
export type ScreenCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScreenCountOutputType
   */
  select?: Prisma.ScreenCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ScreenCountOutputType without action
 */
export type ScreenCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileScreenWhereInput
}

/**
 * ScreenCountOutputType without action
 */
export type ScreenCountOutputTypeCountPermissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PermissionWhereInput
}

/**
 * ScreenCountOutputType without action
 */
export type ScreenCountOutputTypeCountDefault_forArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
}


export type ScreenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  path?: boolean
  description?: boolean
  order?: boolean
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id?: boolean
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
  members?: boolean | Prisma.Screen$membersArgs<ExtArgs>
  permissions?: boolean | Prisma.Screen$permissionsArgs<ExtArgs>
  default_for?: boolean | Prisma.Screen$default_forArgs<ExtArgs>
  _count?: boolean | Prisma.ScreenCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["screen"]>



export type ScreenSelectScalar = {
  id?: boolean
  key?: boolean
  name?: boolean
  path?: boolean
  description?: boolean
  order?: boolean
  is_system?: boolean
  is_active?: boolean
  is_enabled?: boolean
  module_id?: boolean
}

export type ScreenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "name" | "path" | "description" | "order" | "is_system" | "is_active" | "is_enabled" | "module_id", ExtArgs["result"]["screen"]>
export type ScreenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
  members?: boolean | Prisma.Screen$membersArgs<ExtArgs>
  permissions?: boolean | Prisma.Screen$permissionsArgs<ExtArgs>
  default_for?: boolean | Prisma.Screen$default_forArgs<ExtArgs>
  _count?: boolean | Prisma.ScreenCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ScreenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Screen"
  objects: {
    module: Prisma.$ModulePayload<ExtArgs>
    members: Prisma.$ProfileScreenPayload<ExtArgs>[]
    permissions: Prisma.$PermissionPayload<ExtArgs>[]
    default_for: Prisma.$ProfilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    name: string
    path: string | null
    description: string | null
    order: number
    is_system: boolean
    is_active: boolean
    is_enabled: boolean
    module_id: string
  }, ExtArgs["result"]["screen"]>
  composites: {}
}

export type ScreenGetPayload<S extends boolean | null | undefined | ScreenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ScreenPayload, S>

export type ScreenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ScreenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ScreenCountAggregateInputType | true
  }

export interface ScreenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Screen'], meta: { name: 'Screen' } }
  /**
   * Find zero or one Screen that matches the filter.
   * @param {ScreenFindUniqueArgs} args - Arguments to find a Screen
   * @example
   * // Get one Screen
   * const screen = await prisma.screen.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ScreenFindUniqueArgs>(args: Prisma.SelectSubset<T, ScreenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Screen that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ScreenFindUniqueOrThrowArgs} args - Arguments to find a Screen
   * @example
   * // Get one Screen
   * const screen = await prisma.screen.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ScreenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ScreenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Screen that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenFindFirstArgs} args - Arguments to find a Screen
   * @example
   * // Get one Screen
   * const screen = await prisma.screen.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ScreenFindFirstArgs>(args?: Prisma.SelectSubset<T, ScreenFindFirstArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Screen that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenFindFirstOrThrowArgs} args - Arguments to find a Screen
   * @example
   * // Get one Screen
   * const screen = await prisma.screen.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ScreenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ScreenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Screens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Screens
   * const screens = await prisma.screen.findMany()
   * 
   * // Get first 10 Screens
   * const screens = await prisma.screen.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const screenWithIdOnly = await prisma.screen.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ScreenFindManyArgs>(args?: Prisma.SelectSubset<T, ScreenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Screen.
   * @param {ScreenCreateArgs} args - Arguments to create a Screen.
   * @example
   * // Create one Screen
   * const Screen = await prisma.screen.create({
   *   data: {
   *     // ... data to create a Screen
   *   }
   * })
   * 
   */
  create<T extends ScreenCreateArgs>(args: Prisma.SelectSubset<T, ScreenCreateArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Screens.
   * @param {ScreenCreateManyArgs} args - Arguments to create many Screens.
   * @example
   * // Create many Screens
   * const screen = await prisma.screen.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ScreenCreateManyArgs>(args?: Prisma.SelectSubset<T, ScreenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Screen.
   * @param {ScreenDeleteArgs} args - Arguments to delete one Screen.
   * @example
   * // Delete one Screen
   * const Screen = await prisma.screen.delete({
   *   where: {
   *     // ... filter to delete one Screen
   *   }
   * })
   * 
   */
  delete<T extends ScreenDeleteArgs>(args: Prisma.SelectSubset<T, ScreenDeleteArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Screen.
   * @param {ScreenUpdateArgs} args - Arguments to update one Screen.
   * @example
   * // Update one Screen
   * const screen = await prisma.screen.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ScreenUpdateArgs>(args: Prisma.SelectSubset<T, ScreenUpdateArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Screens.
   * @param {ScreenDeleteManyArgs} args - Arguments to filter Screens to delete.
   * @example
   * // Delete a few Screens
   * const { count } = await prisma.screen.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ScreenDeleteManyArgs>(args?: Prisma.SelectSubset<T, ScreenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Screens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Screens
   * const screen = await prisma.screen.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ScreenUpdateManyArgs>(args: Prisma.SelectSubset<T, ScreenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Screen.
   * @param {ScreenUpsertArgs} args - Arguments to update or create a Screen.
   * @example
   * // Update or create a Screen
   * const screen = await prisma.screen.upsert({
   *   create: {
   *     // ... data to create a Screen
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Screen we want to update
   *   }
   * })
   */
  upsert<T extends ScreenUpsertArgs>(args: Prisma.SelectSubset<T, ScreenUpsertArgs<ExtArgs>>): Prisma.Prisma__ScreenClient<runtime.Types.Result.GetResult<Prisma.$ScreenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Screens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenCountArgs} args - Arguments to filter Screens to count.
   * @example
   * // Count the number of Screens
   * const count = await prisma.screen.count({
   *   where: {
   *     // ... the filter for the Screens we want to count
   *   }
   * })
  **/
  count<T extends ScreenCountArgs>(
    args?: Prisma.Subset<T, ScreenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ScreenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Screen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ScreenAggregateArgs>(args: Prisma.Subset<T, ScreenAggregateArgs>): Prisma.PrismaPromise<GetScreenAggregateType<T>>

  /**
   * Group by Screen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScreenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ScreenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ScreenGroupByArgs['orderBy'] }
      : { orderBy?: ScreenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ScreenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetScreenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Screen model
 */
readonly fields: ScreenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Screen.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ScreenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  module<T extends Prisma.ModuleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModuleDefaultArgs<ExtArgs>>): Prisma.Prisma__ModuleClient<runtime.Types.Result.GetResult<Prisma.$ModulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.Screen$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Screen$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileScreenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  permissions<T extends Prisma.Screen$permissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Screen$permissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  default_for<T extends Prisma.Screen$default_forArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Screen$default_forArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Screen model
 */
export interface ScreenFieldRefs {
  readonly id: Prisma.FieldRef<"Screen", 'String'>
  readonly key: Prisma.FieldRef<"Screen", 'String'>
  readonly name: Prisma.FieldRef<"Screen", 'String'>
  readonly path: Prisma.FieldRef<"Screen", 'String'>
  readonly description: Prisma.FieldRef<"Screen", 'String'>
  readonly order: Prisma.FieldRef<"Screen", 'Int'>
  readonly is_system: Prisma.FieldRef<"Screen", 'Boolean'>
  readonly is_active: Prisma.FieldRef<"Screen", 'Boolean'>
  readonly is_enabled: Prisma.FieldRef<"Screen", 'Boolean'>
  readonly module_id: Prisma.FieldRef<"Screen", 'String'>
}
    

// Custom InputTypes
/**
 * Screen findUnique
 */
export type ScreenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter, which Screen to fetch.
   */
  where: Prisma.ScreenWhereUniqueInput
}

/**
 * Screen findUniqueOrThrow
 */
export type ScreenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter, which Screen to fetch.
   */
  where: Prisma.ScreenWhereUniqueInput
}

/**
 * Screen findFirst
 */
export type ScreenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter, which Screen to fetch.
   */
  where?: Prisma.ScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Screens to fetch.
   */
  orderBy?: Prisma.ScreenOrderByWithRelationInput | Prisma.ScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Screens.
   */
  cursor?: Prisma.ScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Screens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Screens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Screens.
   */
  distinct?: Prisma.ScreenScalarFieldEnum | Prisma.ScreenScalarFieldEnum[]
}

/**
 * Screen findFirstOrThrow
 */
export type ScreenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter, which Screen to fetch.
   */
  where?: Prisma.ScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Screens to fetch.
   */
  orderBy?: Prisma.ScreenOrderByWithRelationInput | Prisma.ScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Screens.
   */
  cursor?: Prisma.ScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Screens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Screens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Screens.
   */
  distinct?: Prisma.ScreenScalarFieldEnum | Prisma.ScreenScalarFieldEnum[]
}

/**
 * Screen findMany
 */
export type ScreenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter, which Screens to fetch.
   */
  where?: Prisma.ScreenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Screens to fetch.
   */
  orderBy?: Prisma.ScreenOrderByWithRelationInput | Prisma.ScreenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Screens.
   */
  cursor?: Prisma.ScreenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Screens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Screens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Screens.
   */
  distinct?: Prisma.ScreenScalarFieldEnum | Prisma.ScreenScalarFieldEnum[]
}

/**
 * Screen create
 */
export type ScreenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * The data needed to create a Screen.
   */
  data: Prisma.XOR<Prisma.ScreenCreateInput, Prisma.ScreenUncheckedCreateInput>
}

/**
 * Screen createMany
 */
export type ScreenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Screens.
   */
  data: Prisma.ScreenCreateManyInput | Prisma.ScreenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Screen update
 */
export type ScreenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * The data needed to update a Screen.
   */
  data: Prisma.XOR<Prisma.ScreenUpdateInput, Prisma.ScreenUncheckedUpdateInput>
  /**
   * Choose, which Screen to update.
   */
  where: Prisma.ScreenWhereUniqueInput
}

/**
 * Screen updateMany
 */
export type ScreenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Screens.
   */
  data: Prisma.XOR<Prisma.ScreenUpdateManyMutationInput, Prisma.ScreenUncheckedUpdateManyInput>
  /**
   * Filter which Screens to update
   */
  where?: Prisma.ScreenWhereInput
  /**
   * Limit how many Screens to update.
   */
  limit?: number
}

/**
 * Screen upsert
 */
export type ScreenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * The filter to search for the Screen to update in case it exists.
   */
  where: Prisma.ScreenWhereUniqueInput
  /**
   * In case the Screen found by the `where` argument doesn't exist, create a new Screen with this data.
   */
  create: Prisma.XOR<Prisma.ScreenCreateInput, Prisma.ScreenUncheckedCreateInput>
  /**
   * In case the Screen was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ScreenUpdateInput, Prisma.ScreenUncheckedUpdateInput>
}

/**
 * Screen delete
 */
export type ScreenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
  /**
   * Filter which Screen to delete.
   */
  where: Prisma.ScreenWhereUniqueInput
}

/**
 * Screen deleteMany
 */
export type ScreenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Screens to delete
   */
  where?: Prisma.ScreenWhereInput
  /**
   * Limit how many Screens to delete.
   */
  limit?: number
}

/**
 * Screen.members
 */
export type Screen$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileScreen
   */
  select?: Prisma.ProfileScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileScreen
   */
  omit?: Prisma.ProfileScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileScreenInclude<ExtArgs> | null
  where?: Prisma.ProfileScreenWhereInput
  orderBy?: Prisma.ProfileScreenOrderByWithRelationInput | Prisma.ProfileScreenOrderByWithRelationInput[]
  cursor?: Prisma.ProfileScreenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfileScreenScalarFieldEnum | Prisma.ProfileScreenScalarFieldEnum[]
}

/**
 * Screen.permissions
 */
export type Screen$permissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Permission
   */
  select?: Prisma.PermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Permission
   */
  omit?: Prisma.PermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionInclude<ExtArgs> | null
  where?: Prisma.PermissionWhereInput
  orderBy?: Prisma.PermissionOrderByWithRelationInput | Prisma.PermissionOrderByWithRelationInput[]
  cursor?: Prisma.PermissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PermissionScalarFieldEnum | Prisma.PermissionScalarFieldEnum[]
}

/**
 * Screen.default_for
 */
export type Screen$default_forArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  cursor?: Prisma.ProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Screen without action
 */
export type ScreenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screen
   */
  select?: Prisma.ScreenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screen
   */
  omit?: Prisma.ScreenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenInclude<ExtArgs> | null
}
