
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserProfile
 * 
 */
export type UserProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$UserProfilePayload>

export type AggregateUserProfile = {
  _count: UserProfileCountAggregateOutputType | null
  _min: UserProfileMinAggregateOutputType | null
  _max: UserProfileMaxAggregateOutputType | null
}

export type UserProfileMinAggregateOutputType = {
  user_id: string | null
  profile_id: string | null
}

export type UserProfileMaxAggregateOutputType = {
  user_id: string | null
  profile_id: string | null
}

export type UserProfileCountAggregateOutputType = {
  user_id: number
  profile_id: number
  _all: number
}


export type UserProfileMinAggregateInputType = {
  user_id?: true
  profile_id?: true
}

export type UserProfileMaxAggregateInputType = {
  user_id?: true
  profile_id?: true
}

export type UserProfileCountAggregateInputType = {
  user_id?: true
  profile_id?: true
  _all?: true
}

export type UserProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserProfile to aggregate.
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProfiles to fetch.
   */
  orderBy?: Prisma.UserProfileOrderByWithRelationInput | Prisma.UserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserProfiles
  **/
  _count?: true | UserProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserProfileMaxAggregateInputType
}

export type GetUserProfileAggregateType<T extends UserProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateUserProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateUserProfile[P]>
}




export type UserProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserProfileWhereInput
  orderBy?: Prisma.UserProfileOrderByWithAggregationInput | Prisma.UserProfileOrderByWithAggregationInput[]
  by: Prisma.UserProfileScalarFieldEnum[] | Prisma.UserProfileScalarFieldEnum
  having?: Prisma.UserProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserProfileCountAggregateInputType | true
  _min?: UserProfileMinAggregateInputType
  _max?: UserProfileMaxAggregateInputType
}

export type UserProfileGroupByOutputType = {
  user_id: string
  profile_id: string
  _count: UserProfileCountAggregateOutputType | null
  _min: UserProfileMinAggregateOutputType | null
  _max: UserProfileMaxAggregateOutputType | null
}

export type GetUserProfileGroupByPayload<T extends UserProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserProfileGroupByOutputType[P]>
      }
    >
  >



export type UserProfileWhereInput = {
  AND?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[]
  OR?: Prisma.UserProfileWhereInput[]
  NOT?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[]
  user_id?: Prisma.StringFilter<"UserProfile"> | string
  profile_id?: Prisma.StringFilter<"UserProfile"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}

export type UserProfileOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  profile?: Prisma.ProfileOrderByWithRelationInput
  _relevance?: Prisma.UserProfileOrderByRelevanceInput
}

export type UserProfileWhereUniqueInput = Prisma.AtLeast<{
  user_id_profile_id?: Prisma.UserProfileUser_idProfile_idCompoundUniqueInput
  AND?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[]
  OR?: Prisma.UserProfileWhereInput[]
  NOT?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[]
  user_id?: Prisma.StringFilter<"UserProfile"> | string
  profile_id?: Prisma.StringFilter<"UserProfile"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}, "user_id_profile_id">

export type UserProfileOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  _count?: Prisma.UserProfileCountOrderByAggregateInput
  _max?: Prisma.UserProfileMaxOrderByAggregateInput
  _min?: Prisma.UserProfileMinOrderByAggregateInput
}

export type UserProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserProfileScalarWhereWithAggregatesInput | Prisma.UserProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserProfileScalarWhereWithAggregatesInput | Prisma.UserProfileScalarWhereWithAggregatesInput[]
  user_id?: Prisma.StringWithAggregatesFilter<"UserProfile"> | string
  profile_id?: Prisma.StringWithAggregatesFilter<"UserProfile"> | string
}

export type UserProfileCreateInput = {
  user: Prisma.UserCreateNestedOneWithoutProfilesInput
  profile: Prisma.ProfileCreateNestedOneWithoutUsersInput
}

export type UserProfileUncheckedCreateInput = {
  user_id: string
  profile_id: string
}

export type UserProfileUpdateInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
  profile?: Prisma.ProfileUpdateOneRequiredWithoutUsersNestedInput
}

export type UserProfileUncheckedUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProfileCreateManyInput = {
  user_id: string
  profile_id: string
}

export type UserProfileUpdateManyMutationInput = {

}

export type UserProfileUncheckedUpdateManyInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProfileListRelationFilter = {
  every?: Prisma.UserProfileWhereInput
  some?: Prisma.UserProfileWhereInput
  none?: Prisma.UserProfileWhereInput
}

export type UserProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserProfileOrderByRelevanceInput = {
  fields: Prisma.UserProfileOrderByRelevanceFieldEnum | Prisma.UserProfileOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserProfileUser_idProfile_idCompoundUniqueInput = {
  user_id: string
  profile_id: string
}

export type UserProfileCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
}

export type UserProfileMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
}

export type UserProfileMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
}

export type UserProfileCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput> | Prisma.UserProfileCreateWithoutUserInput[] | Prisma.UserProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutUserInput | Prisma.UserProfileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserProfileCreateManyUserInputEnvelope
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
}

export type UserProfileUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput> | Prisma.UserProfileCreateWithoutUserInput[] | Prisma.UserProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutUserInput | Prisma.UserProfileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserProfileCreateManyUserInputEnvelope
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
}

export type UserProfileUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput> | Prisma.UserProfileCreateWithoutUserInput[] | Prisma.UserProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutUserInput | Prisma.UserProfileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserProfileUpsertWithWhereUniqueWithoutUserInput | Prisma.UserProfileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserProfileCreateManyUserInputEnvelope
  set?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  disconnect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  delete?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  update?: Prisma.UserProfileUpdateWithWhereUniqueWithoutUserInput | Prisma.UserProfileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserProfileUpdateManyWithWhereWithoutUserInput | Prisma.UserProfileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
}

export type UserProfileUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput> | Prisma.UserProfileCreateWithoutUserInput[] | Prisma.UserProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutUserInput | Prisma.UserProfileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserProfileUpsertWithWhereUniqueWithoutUserInput | Prisma.UserProfileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserProfileCreateManyUserInputEnvelope
  set?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  disconnect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  delete?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  update?: Prisma.UserProfileUpdateWithWhereUniqueWithoutUserInput | Prisma.UserProfileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserProfileUpdateManyWithWhereWithoutUserInput | Prisma.UserProfileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
}

export type UserProfileCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput> | Prisma.UserProfileCreateWithoutProfileInput[] | Prisma.UserProfileUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutProfileInput | Prisma.UserProfileCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.UserProfileCreateManyProfileInputEnvelope
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
}

export type UserProfileUncheckedCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput> | Prisma.UserProfileCreateWithoutProfileInput[] | Prisma.UserProfileUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutProfileInput | Prisma.UserProfileCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.UserProfileCreateManyProfileInputEnvelope
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
}

export type UserProfileUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput> | Prisma.UserProfileCreateWithoutProfileInput[] | Prisma.UserProfileUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutProfileInput | Prisma.UserProfileCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.UserProfileUpsertWithWhereUniqueWithoutProfileInput | Prisma.UserProfileUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.UserProfileCreateManyProfileInputEnvelope
  set?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  disconnect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  delete?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  update?: Prisma.UserProfileUpdateWithWhereUniqueWithoutProfileInput | Prisma.UserProfileUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.UserProfileUpdateManyWithWhereWithoutProfileInput | Prisma.UserProfileUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
}

export type UserProfileUncheckedUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput> | Prisma.UserProfileCreateWithoutProfileInput[] | Prisma.UserProfileUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.UserProfileCreateOrConnectWithoutProfileInput | Prisma.UserProfileCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.UserProfileUpsertWithWhereUniqueWithoutProfileInput | Prisma.UserProfileUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.UserProfileCreateManyProfileInputEnvelope
  set?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  disconnect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  delete?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  connect?: Prisma.UserProfileWhereUniqueInput | Prisma.UserProfileWhereUniqueInput[]
  update?: Prisma.UserProfileUpdateWithWhereUniqueWithoutProfileInput | Prisma.UserProfileUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.UserProfileUpdateManyWithWhereWithoutProfileInput | Prisma.UserProfileUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
}

export type UserProfileCreateWithoutUserInput = {
  profile: Prisma.ProfileCreateNestedOneWithoutUsersInput
}

export type UserProfileUncheckedCreateWithoutUserInput = {
  profile_id: string
}

export type UserProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.UserProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput>
}

export type UserProfileCreateManyUserInputEnvelope = {
  data: Prisma.UserProfileCreateManyUserInput | Prisma.UserProfileCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserProfileUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.UserProfileUpdateWithoutUserInput, Prisma.UserProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserProfileCreateWithoutUserInput, Prisma.UserProfileUncheckedCreateWithoutUserInput>
}

export type UserProfileUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.UserProfileUpdateWithoutUserInput, Prisma.UserProfileUncheckedUpdateWithoutUserInput>
}

export type UserProfileUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserProfileScalarWhereInput
  data: Prisma.XOR<Prisma.UserProfileUpdateManyMutationInput, Prisma.UserProfileUncheckedUpdateManyWithoutUserInput>
}

export type UserProfileScalarWhereInput = {
  AND?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
  OR?: Prisma.UserProfileScalarWhereInput[]
  NOT?: Prisma.UserProfileScalarWhereInput | Prisma.UserProfileScalarWhereInput[]
  user_id?: Prisma.StringFilter<"UserProfile"> | string
  profile_id?: Prisma.StringFilter<"UserProfile"> | string
}

export type UserProfileCreateWithoutProfileInput = {
  user: Prisma.UserCreateNestedOneWithoutProfilesInput
}

export type UserProfileUncheckedCreateWithoutProfileInput = {
  user_id: string
}

export type UserProfileCreateOrConnectWithoutProfileInput = {
  where: Prisma.UserProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput>
}

export type UserProfileCreateManyProfileInputEnvelope = {
  data: Prisma.UserProfileCreateManyProfileInput | Prisma.UserProfileCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type UserProfileUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.UserProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.UserProfileUpdateWithoutProfileInput, Prisma.UserProfileUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.UserProfileCreateWithoutProfileInput, Prisma.UserProfileUncheckedCreateWithoutProfileInput>
}

export type UserProfileUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.UserProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.UserProfileUpdateWithoutProfileInput, Prisma.UserProfileUncheckedUpdateWithoutProfileInput>
}

export type UserProfileUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.UserProfileScalarWhereInput
  data: Prisma.XOR<Prisma.UserProfileUpdateManyMutationInput, Prisma.UserProfileUncheckedUpdateManyWithoutProfileInput>
}

export type UserProfileCreateManyUserInput = {
  profile_id: string
}

export type UserProfileUpdateWithoutUserInput = {
  profile?: Prisma.ProfileUpdateOneRequiredWithoutUsersNestedInput
}

export type UserProfileUncheckedUpdateWithoutUserInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProfileUncheckedUpdateManyWithoutUserInput = {
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProfileCreateManyProfileInput = {
  user_id: string
}

export type UserProfileUpdateWithoutProfileInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
}

export type UserProfileUncheckedUpdateWithoutProfileInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProfileUncheckedUpdateManyWithoutProfileInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  profile_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userProfile"]>



export type UserProfileSelectScalar = {
  user_id?: boolean
  profile_id?: boolean
}

export type UserProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "profile_id", ExtArgs["result"]["userProfile"]>
export type UserProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}

export type $UserProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserProfile"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    profile: Prisma.$ProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: string
    profile_id: string
  }, ExtArgs["result"]["userProfile"]>
  composites: {}
}

export type UserProfileGetPayload<S extends boolean | null | undefined | UserProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserProfilePayload, S>

export type UserProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserProfileCountAggregateInputType | true
  }

export interface UserProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserProfile'], meta: { name: 'UserProfile' } }
  /**
   * Find zero or one UserProfile that matches the filter.
   * @param {UserProfileFindUniqueArgs} args - Arguments to find a UserProfile
   * @example
   * // Get one UserProfile
   * const userProfile = await prisma.userProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, UserProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserProfileFindUniqueOrThrowArgs} args - Arguments to find a UserProfile
   * @example
   * // Get one UserProfile
   * const userProfile = await prisma.userProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileFindFirstArgs} args - Arguments to find a UserProfile
   * @example
   * // Get one UserProfile
   * const userProfile = await prisma.userProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, UserProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileFindFirstOrThrowArgs} args - Arguments to find a UserProfile
   * @example
   * // Get one UserProfile
   * const userProfile = await prisma.userProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserProfiles
   * const userProfiles = await prisma.userProfile.findMany()
   * 
   * // Get first 10 UserProfiles
   * const userProfiles = await prisma.userProfile.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const userProfileWithUser_idOnly = await prisma.userProfile.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends UserProfileFindManyArgs>(args?: Prisma.SelectSubset<T, UserProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserProfile.
   * @param {UserProfileCreateArgs} args - Arguments to create a UserProfile.
   * @example
   * // Create one UserProfile
   * const UserProfile = await prisma.userProfile.create({
   *   data: {
   *     // ... data to create a UserProfile
   *   }
   * })
   * 
   */
  create<T extends UserProfileCreateArgs>(args: Prisma.SelectSubset<T, UserProfileCreateArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserProfiles.
   * @param {UserProfileCreateManyArgs} args - Arguments to create many UserProfiles.
   * @example
   * // Create many UserProfiles
   * const userProfile = await prisma.userProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, UserProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a UserProfile.
   * @param {UserProfileDeleteArgs} args - Arguments to delete one UserProfile.
   * @example
   * // Delete one UserProfile
   * const UserProfile = await prisma.userProfile.delete({
   *   where: {
   *     // ... filter to delete one UserProfile
   *   }
   * })
   * 
   */
  delete<T extends UserProfileDeleteArgs>(args: Prisma.SelectSubset<T, UserProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserProfile.
   * @param {UserProfileUpdateArgs} args - Arguments to update one UserProfile.
   * @example
   * // Update one UserProfile
   * const userProfile = await prisma.userProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserProfileUpdateArgs>(args: Prisma.SelectSubset<T, UserProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserProfiles.
   * @param {UserProfileDeleteManyArgs} args - Arguments to filter UserProfiles to delete.
   * @example
   * // Delete a few UserProfiles
   * const { count } = await prisma.userProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserProfiles
   * const userProfile = await prisma.userProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, UserProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one UserProfile.
   * @param {UserProfileUpsertArgs} args - Arguments to update or create a UserProfile.
   * @example
   * // Update or create a UserProfile
   * const userProfile = await prisma.userProfile.upsert({
   *   create: {
   *     // ... data to create a UserProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserProfile we want to update
   *   }
   * })
   */
  upsert<T extends UserProfileUpsertArgs>(args: Prisma.SelectSubset<T, UserProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileCountArgs} args - Arguments to filter UserProfiles to count.
   * @example
   * // Count the number of UserProfiles
   * const count = await prisma.userProfile.count({
   *   where: {
   *     // ... the filter for the UserProfiles we want to count
   *   }
   * })
  **/
  count<T extends UserProfileCountArgs>(
    args?: Prisma.Subset<T, UserProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserProfileAggregateArgs>(args: Prisma.Subset<T, UserProfileAggregateArgs>): Prisma.PrismaPromise<GetUserProfileAggregateType<T>>

  /**
   * Group by UserProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserProfileGroupByArgs['orderBy'] }
      : { orderBy?: UserProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserProfile model
 */
readonly fields: UserProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserProfile model
 */
export interface UserProfileFieldRefs {
  readonly user_id: Prisma.FieldRef<"UserProfile", 'String'>
  readonly profile_id: Prisma.FieldRef<"UserProfile", 'String'>
}
    

// Custom InputTypes
/**
 * UserProfile findUnique
 */
export type UserProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter, which UserProfile to fetch.
   */
  where: Prisma.UserProfileWhereUniqueInput
}

/**
 * UserProfile findUniqueOrThrow
 */
export type UserProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter, which UserProfile to fetch.
   */
  where: Prisma.UserProfileWhereUniqueInput
}

/**
 * UserProfile findFirst
 */
export type UserProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter, which UserProfile to fetch.
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProfiles to fetch.
   */
  orderBy?: Prisma.UserProfileOrderByWithRelationInput | Prisma.UserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserProfiles.
   */
  cursor?: Prisma.UserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserProfiles.
   */
  distinct?: Prisma.UserProfileScalarFieldEnum | Prisma.UserProfileScalarFieldEnum[]
}

/**
 * UserProfile findFirstOrThrow
 */
export type UserProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter, which UserProfile to fetch.
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProfiles to fetch.
   */
  orderBy?: Prisma.UserProfileOrderByWithRelationInput | Prisma.UserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserProfiles.
   */
  cursor?: Prisma.UserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserProfiles.
   */
  distinct?: Prisma.UserProfileScalarFieldEnum | Prisma.UserProfileScalarFieldEnum[]
}

/**
 * UserProfile findMany
 */
export type UserProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter, which UserProfiles to fetch.
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProfiles to fetch.
   */
  orderBy?: Prisma.UserProfileOrderByWithRelationInput | Prisma.UserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserProfiles.
   */
  cursor?: Prisma.UserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserProfiles.
   */
  distinct?: Prisma.UserProfileScalarFieldEnum | Prisma.UserProfileScalarFieldEnum[]
}

/**
 * UserProfile create
 */
export type UserProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a UserProfile.
   */
  data: Prisma.XOR<Prisma.UserProfileCreateInput, Prisma.UserProfileUncheckedCreateInput>
}

/**
 * UserProfile createMany
 */
export type UserProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserProfiles.
   */
  data: Prisma.UserProfileCreateManyInput | Prisma.UserProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserProfile update
 */
export type UserProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a UserProfile.
   */
  data: Prisma.XOR<Prisma.UserProfileUpdateInput, Prisma.UserProfileUncheckedUpdateInput>
  /**
   * Choose, which UserProfile to update.
   */
  where: Prisma.UserProfileWhereUniqueInput
}

/**
 * UserProfile updateMany
 */
export type UserProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserProfiles.
   */
  data: Prisma.XOR<Prisma.UserProfileUpdateManyMutationInput, Prisma.UserProfileUncheckedUpdateManyInput>
  /**
   * Filter which UserProfiles to update
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * Limit how many UserProfiles to update.
   */
  limit?: number
}

/**
 * UserProfile upsert
 */
export type UserProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the UserProfile to update in case it exists.
   */
  where: Prisma.UserProfileWhereUniqueInput
  /**
   * In case the UserProfile found by the `where` argument doesn't exist, create a new UserProfile with this data.
   */
  create: Prisma.XOR<Prisma.UserProfileCreateInput, Prisma.UserProfileUncheckedCreateInput>
  /**
   * In case the UserProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserProfileUpdateInput, Prisma.UserProfileUncheckedUpdateInput>
}

/**
 * UserProfile delete
 */
export type UserProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  /**
   * Filter which UserProfile to delete.
   */
  where: Prisma.UserProfileWhereUniqueInput
}

/**
 * UserProfile deleteMany
 */
export type UserProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserProfiles to delete
   */
  where?: Prisma.UserProfileWhereInput
  /**
   * Limit how many UserProfiles to delete.
   */
  limit?: number
}

/**
 * UserProfile without action
 */
export type UserProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
}
